Support ghcr tags

diff --git a/bin/checkupd-containers b/bin/checkupd-containers
--- a/bin/checkupd-containers
+++ b/bin/checkupd-containers
@@ -27,9 +27,25 @@ _get_latest_tags() {
   fi
 
   printf -- '\nContainer: %s/%s\n' "${_org}" "${_image}"
-  curl -s "https://hub.docker.com/v2/namespaces/${_org}/repositories/${_image}/tags?page_size=${_number_of_tags}" | grep -o '"name": *"[^"]*' | grep --color -o '[^"]*$' || {
-    printf -- 'Failed to lookup container on registry: %s\n' "${_container}"
-  }
+  case "${_container}" in
+    docker.io/*)
+      curl -s "https://hub.docker.com/v2/namespaces/${_org}/repositories/${_image}/tags?page_size=${_number_of_tags}" | grep -o '"name": *"[^"]*' | grep --color -o '[^"]*$' || {
+        printf -- 'Failed to lookup container on registry: %s\n' "${_container}"
+      }
+      ;;
+    ghcr.io/*)
+      # First we get a token for a public repo
+      _gh_token="$(curl -s "https://ghcr.io/token?scope=repository:${_org}/${_image}:pull" | tr ':' ' ' | sed 's/"//g' | sed 's/}//g' | awk '{ print $2 }')"
+
+      # And then we do this - oh baby!
+      curl -s -H "Authorization: Bearer ${_gh_token}" "https://ghcr.io/v2/${_org}/${_image}/tags/list" | grep --color -o '\[.*\]' | sed 's/\[//g' | sed 's/\]//g' | sed 's/"//g' | tr ',' '\n' | head -n "${_number_of_tags}" | grep --color '.*' || {
+        printf -- 'Failed to lookup container on registry: %s\n' "${_container}"
+      }
+      ;;
+    *)
+      printf -- 'Unsupported container registry: %s\n' "${_container}"
+      ;;
+  esac
 
   unset _container
   unset _number_of_tags
