Update containers, add new network instead of bridge

diff --git a/dots/scripts/containers/active/adguardhome/adguardhome b/dots/scripts/containers/active/adguardhome/adguardhome
--- a/dots/scripts/containers/active/adguardhome/adguardhome
+++ b/dots/scripts/containers/active/adguardhome/adguardhome
@@ -60,6 +60,19 @@ _prep_mounts() {
   return 0
 }
 
+_prep_network() {
+  _runas podman network create \
+    --ignore \
+    --disable-dns \
+    --driver "bridge" \
+    "${_name}" || {
+    printf -- 'Failed to create podman network bridge: %s\n' "${_name}"
+    return 1
+  }
+
+  return 0
+}
+
 _prep_caps() {
   _caps=""
   _caps="${_caps} --cap-add NET_BIND_SERVICE"
@@ -150,6 +163,7 @@ _containerize() {
     --name "${_name}" --hostname "${_name}" \
     --security-opt no-new-privileges:true --cap-drop ALL \
     --add-host "localhost:127.0.0.1" \
+    --network="${_name}" \
     ${_mounts} \
     ${_ports} \
     ${_caps} \
@@ -185,6 +199,7 @@ main() {
   _prep_mounts || return 1
   _prep_ports || return 1
   _prep_caps || return 1
+  _prep_network || return 1
 
   # How do we run?
   if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
