Check that script alias exists

diff --git a/dots/scripts/containers/pull-containers b/dots/scripts/containers/pull-containers
--- a/dots/scripts/containers/pull-containers
+++ b/dots/scripts/containers/pull-containers
@@ -1,10 +1,12 @@
 #!/bin/sh
 
 _pull() {
-  "$1" pull || {
-    printf -- 'Failed to pull for delegate: %s\n' "$1"
-    return 1
-  }
+  if [ -x "$1" ]; then
+    "$1" pull || {
+      printf -- 'Failed to pull for delegate: %s\n' "$1"
+      return 1
+    }
+  fi
 
   return 0
 }
