Update container scripts
We expect and support only podman now

diff --git a/.containers/bin/jellyfin b/.containers/bin/jellyfin
--- a/.containers/bin/jellyfin
+++ b/.containers/bin/jellyfin
@@ -4,67 +4,115 @@ readonly _name="jellyfin"
 readonly _image="docker.io/jellyfin/jellyfin"
 readonly _tag="10.7.7"
 
-# Use docker or podman (priority podman)
-_cmd="sudo docker"
-_userns=""
-if command -v podman >/dev/null; then
-  _cmd="podman"
+# Use podman, don't use docker
+readonly _cmd="podman"
+
+_prep_mounts() {
+  readonly _mount1="${HOME}/.local/etc/containers/${_name}/cache"
+  readonly _mount2="${HOME}/.local/etc/containers/${_name}/config"
+  readonly _mount3="${HOME}/.local/etc/containers/${_name}/media"
+  readonly _mount4="${HOME}/.local/etc/containers/${_name}/.cache" # Transcode shader cache
+
+  mkdir -p "${_mount1}" || return 1
+  mkdir -p "${_mount2}" || return 1
+  mkdir -p "${_mount3}" || return 1
+  mkdir -p "${_mount4}" || return 1
+
+  _mounts=""
+  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/cache"
+  _mounts="${_mounts} --mount type=bind,source=${_mount2},target=/config"
+  _mounts="${_mounts} --mount type=bind,source=${_mount3},target=/media"
+  _mounts="${_mounts} --mount type=bind,source=${_mount4},target=/.cache"
+  readonly _mounts
+  return 0
+}
+
+_prep_caps() {
+  _caps=""
+
+  # No caps
+
+  readonly _caps
+  return 0
+}
+
+_prep_ports() {
+  _ports=""
+
+  _ports="${_ports} -p 127.0.0.1:8096:8096/tcp"
+
+  readonly _ports
+  return 0
+}
+
+_check_user() {
+  if [ "$(id -u)" -eq 0 ]; then
+    printf -- 'You must run this as a rootless container\n'
+    return 1
+  fi
 
   # Need this userns option that is podman specific or we have random OCI permission error
   _userns="--userns keep-id"
-fi
-readonly _cmd
+  readonly _userns
 
-if [ "$(id -u)" -eq 0 ]; then
-  printf -- 'You must run this as a rootless container\n'
-  exit 1
-fi
+  return 0
+}
 
-# Prep the directories
-readonly _mount1="${HOME}/.local/etc/containers/${_name}/cache"
-readonly _mount2="${HOME}/.local/etc/containers/${_name}/config"
-readonly _mount3="${HOME}/.local/etc/containers/${_name}/media"
-readonly _mount4="${HOME}/.local/etc/containers/${_name}/.cache" # Transcode shader cache
-mkdir -p "${_mount1}" || exit 1
-mkdir -p "${_mount2}" || exit 1
-mkdir -p "${_mount3}" || exit 1
-mkdir -p "${_mount4}" || exit 1
+_check_health() {
+  _health=""
 
-# Let it daemonize
-if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
-  shift
-  _how="-d"
-else
-  _how="--rm"
-fi
-readonly _how
+  # systemd does not like spawning this healthcheck
+  if [ "$(uname)" != "Darwin" ]; then
+    _health="--health-cmd none"
+  fi
 
-# systemd --user does not like the healthcheck command
-# disable it.
-_health=""
-if [ "$(uname)" != "Darwin" ]; then
-  _health="--health-cmd none"
-fi
+  readonly _health
 
-# Log the commands we use next
-# Fail on errors
-# Fail on unassigned
-set -xeu
+  return 0
+}
 
-# Don't quote so that if user is empty it still expands
-#
-# shellcheck disable=SC2086
-exec ${_cmd} run ${_how} \
-  --name "${_name}" --hostname "${_name}" \
-  --security-opt no-new-privileges:true --cap-drop ALL \
-  --mount type=bind,source="${_mount1}",target=/cache \
-  --mount type=bind,source="${_mount2}",target=/config \
-  --mount type=bind,source="${_mount3}",target=/media \
-  --mount type=bind,source="${_mount4}",target=/.cache \
-  -p 127.0.0.1:8096:8096/tcp \
-  --group-add=989 \
-  --device /dev/dri/renderD128:/dev/dri/renderD128 \
-  --device /dev/dri/card0:/dev/dri/card0 \
-  ${_health} \
-  ${_userns} \
-  "${_image}:${_tag}" "$@"
+_containerize() {
+  # Log the commands we use next
+  # Fail on errors
+  # Fail on unassigned
+  set -xeu
+
+  # Don't quote so that if user is empty it still expands
+  #
+  # shellcheck disable=SC2086
+  exec ${_cmd} run ${_how} \
+    --name "${_name}" --hostname "${_name}" \
+    --security-opt no-new-privileges:true --cap-drop ALL \
+    --group-add=989 \
+    --device /dev/dri/renderD128:/dev/dri/renderD128 \
+    --device /dev/dri/card0:/dev/dri/card0 \
+    ${_mounts} \
+    ${_ports} \
+    ${_caps} \
+    ${_userns} \
+    ${_health} \
+    "${_image}:${_tag}" "$@"
+}
+
+main() {
+  _check_user || return 1
+  _check_health || return 1
+  _prep_mounts || return 1
+  _prep_ports || return 1
+  _prep_caps || return 1
+
+  # How do we run?
+  if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
+    shift
+    _how="-d --restart=unless-stopped"
+  else
+    _how="--rm -i -t"
+  fi
+  readonly _how
+
+  _containerize "$@" || return 1
+  return 0
+}
+
+main "$@" || exit 1
+exit 0
diff --git a/.containers/bin/stonk-bot b/.containers/bin/stonk-bot
--- a/.containers/bin/stonk-bot
+++ b/.containers/bin/stonk-bot
@@ -4,37 +4,89 @@ readonly _name="stonk-bot"
 readonly _image="localhost/pyamsoft/stonk-bot"
 readonly _tag="latest"
 
-# Use docker or podman (priority podman)
-_cmd="sudo docker"
-if command -v podman >/dev/null; then
-  _cmd="podman"
-fi
-readonly _cmd
+# Use podman, don't use docker
+readonly _cmd="podman"
 
-if [ "$(id -u)" -eq 0 ]; then
-  printf -- 'You must run this as a rootless container\n'
-  exit 1
-fi
+_prep_mounts() {
+  # No mounts
+  readonly _mounts
+  return 0
+}
 
-# Let it daemonize
-if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
-  shift
-  _how="-d"
-else
-  _how="--rm"
-fi
-readonly _how
+_prep_caps() {
+  _caps=""
 
-# Log the commands we use next
-# Fail on errors
-# Fail on unassigned
-set -xeu
+  # No caps
 
-# Don't quote so that if user is empty it still expands
-#
-# shellcheck disable=SC2086
-exec ${_cmd} run ${_how} \
-  --name "${_name}" --hostname "${_name}" \
-  --security-opt no-new-privileges:true --cap-drop ALL \
-  --init \
-  "${_image}:${_tag}" "$@"
+  readonly _caps
+  return 0
+}
+
+_prep_ports() {
+  _ports=""
+
+  # No ports
+
+  readonly _ports
+  return 0
+}
+
+_check_user() {
+  if [ "$(id -u)" -eq 0 ]; then
+    printf -- 'You must run this as a rootless container\n'
+    return 1
+  fi
+
+  _userns=""
+  # No user namespace
+  readonly _userns
+
+  return 0
+}
+
+_check_health() {
+  _health=""
+  # No healthcheck
+  readonly _health
+
+  return 0
+}
+
+_containerize() {
+  # Log the commands we use next
+  # Fail on errors
+  # Fail on unassigned
+  set -xeu
+
+  # Don't quote so that if user is empty it still expands
+  #
+  # shellcheck disable=SC2086
+  exec ${_cmd} run ${_how} \
+    --security-opt no-new-privileges:true --cap-drop ALL \
+    --init \
+    ${_mounts} \
+    ${_ports} \
+    ${_caps} \
+    ${_userns} \
+    ${_health} \
+    "${_image}:${_tag}" "$@"
+}
+
+main() {
+  _check_user || return 1
+  _check_health || return 1
+  _prep_mounts || return 1
+  _prep_ports || return 1
+  _prep_caps || return 1
+
+  # How do we run?
+  _how="--rm -i -t"
+  readonly _how
+
+  _containerize "$@" || return 1
+  return 0
+}
+
+
+main "$@" || exit 1
+exit 0
diff --git a/.containers/bin/syncthing b/.containers/bin/syncthing
--- a/.containers/bin/syncthing
+++ b/.containers/bin/syncthing
@@ -4,76 +4,112 @@ readonly _name="syncthing"
 readonly _image="docker.io/syncthing/syncthing"
 readonly _tag="1.23.6"
 
-# Use docker or podman (priority podman)
-_cmd="sudo docker"
-_userns=""
-if command -v podman >/dev/null; then
-  _cmd="podman"
+# Use podman, don't use docker
+readonly _cmd="podman"
 
-  # Need this userns option that is podman specific or we have random OCI permission error
-  # Can't apply on Mac because our VM runs as root for adguardhome
-  if [ "$(uname)" != "Darwin" ]; then
+_prep_mounts() {
+  readonly _mount1="${HOME}/.local/etc/containers/${_name}/work"
+
+  mkdir -p "${_mount1}" || return 1
+
+  _mounts=""
+  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/var/syncthing"
+  readonly _mounts
+  return 0
+}
+
+_prep_caps() {
+  _caps=""
+  _caps="${_caps} --cap-add DAC_OVERRIDE"
+  _caps="${_caps} --cap-add CHOWN"
+  _caps="${_caps} --cap-add SETGID"
+  _caps="${_caps} --cap-add SETUID"
+  readonly _caps
+  return 0
+}
+
+_prep_ports() {
+  _ports=""
+
+  _ports="${_ports} -p 127.0.0.1:8384:8384/tcp"
+  _ports="${_ports} -p 127.0.0.1:22000:22000/tcp"
+  _ports="${_ports} -p 127.0.0.1:22000:22000/udp"
+  _ports="${_ports} -p 127.0.0.1:21027:21027/udp"
+
+  readonly _ports
+  return 0
+}
+
+_check_user() {
+  if [ "$(id -u)" -eq 0 ]; then
+    printf -- 'You must run this as a rootless container\n'
+    return 1
+  fi
+
+  _userns=""
+
+  # On MacOS we need to own the files to chown them
+  # because just VM things
+  if [ "$(uname)" = "Darwin" ]; then
+    _userns="--user=$(id -u):$(id -g)"
+  else
+    # Otherwise we keep OCI
     _userns="--userns keep-id"
   fi
-fi
-readonly _cmd
 
-if [ "$(id -u)" -eq 0 ]; then
-  printf -- 'You must run this as a rootless container\n'
-  exit 1
-fi
+  readonly _userns
 
-# Prep the directories
-readonly _mount1="${HOME}/.local/etc/containers/${_name}/work"
-mkdir -p "${_mount1}" || exit 1
+  return 0
+}
 
-# Let it daemonize
-if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
-  shift
-  _how="-d"
-else
-  _how="--rm"
-fi
-readonly _how
+_check_health() {
+  _health=""
+  # No healthcheck
+  readonly _health
 
-# On MacOS we need to own the files to chown them
-# because just VM things
-if [ "$(uname)" = "Darwin" ]; then
-  _user="--user=$(id -u):$(id -g)"
-else
-  _user=""
-fi
+  return 0
+}
 
-# systemd --user does not like the healthcheck command
-# disable it.
-_health=""
-if [ "$(uname)" != "Darwin" ]; then
-  _health="--health-cmd none"
-fi
+_containerize() {
+  # Log the commands we use next
+  # Fail on errors
+  # Fail on unassigned
+  set -xeu
 
-# Log the commands we use next
-# Fail on errors
-# Fail on unassigned
-set -xeu
+  # Don't quote so that if user is empty it still expands
+  #
+  # shellcheck disable=SC2086
+  exec ${_cmd} run ${_how} \
+    --security-opt no-new-privileges:true --cap-drop ALL \
+    -e STGUIADDRESS= \
+    -e STNODEFAULTFOLDER=1 \
+    ${_mounts} \
+    ${_ports} \
+    ${_caps} \
+    ${_userns} \
+    ${_health} \
+    "${_image}:${_tag}" "$@"
+}
 
-# Don't quote so that if user is empty it still expands
-#
-# shellcheck disable=SC2086
-exec ${_cmd} run ${_how} \
-  --name "${_name}" --hostname "${_name}" \
-  --security-opt no-new-privileges:true --cap-drop ALL \
-  --mount type=bind,source="${_mount1}",target=/var/syncthing \
-  -p 127.0.0.1:8384:8384/tcp \
-  -p 127.0.0.1:22000:22000/tcp \
-  -p 127.0.0.1:22000:22000/udp \
-  -p 127.0.0.1:21027:21027/udp \
-  --cap-add DAC_OVERRIDE \
-  --cap-add CHOWN \
-  --cap-add SETGID \
-  --cap-add SETUID \
-  -e STGUIADDRESS= \
-  -e STNODEFAULTFOLDER=1 \
-  ${_health} \
-  ${_user} \
-  ${_userns} \
-  "${_image}:${_tag}" "$@"
+main() {
+  _check_user || return 1
+  _check_health || return 1
+  _prep_mounts || return 1
+  _prep_ports || return 1
+  _prep_caps || return 1
+
+  # How do we run?
+  if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
+    shift
+    _how="-d --restart=unless-stopped"
+  else
+    _how="--rm -i -t"
+  fi
+  readonly _how
+
+  _containerize "$@" || return 1
+  return 0
+}
+
+main "$@" || exit 1
+exit 0
diff --git a/.containers/bin/uptime-kuma b/.containers/bin/uptime-kuma
--- a/.containers/bin/uptime-kuma
+++ b/.containers/bin/uptime-kuma
@@ -4,51 +4,101 @@ readonly _name="uptime-kuma"
 readonly _image="docker.io/louislam/uptime-kuma"
 readonly _tag="1.22.1"
 
-# Use docker or podman (priority podman)
-_cmd="sudo docker"
-if command -v podman >/dev/null; then
-  _cmd="podman"
-fi
-readonly _cmd
+# Use podman, don't use docker
+readonly _cmd="podman"
 
-if [ "$(id -u)" -eq 0 ]; then
-  printf -- 'You must run this as a rootless container\n'
-  exit 1
-fi
+_prep_mounts() {
+  readonly _mount1="${HOME}/.local/etc/containers/${_name}/data"
 
-# Let it daemonize
-if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
-  shift
-  _how="-d"
-else
-  _how="--rm"
-fi
-readonly _how
+  mkdir -p "${_mount1}" || return 1
 
-# Prep the directories
-readonly _mount1="${HOME}/.local/etc/containers/${_name}/data"
-mkdir -p "${_mount1}" || exit 1
+  _mounts=""
+  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/app/data"
+  readonly _mounts
+  return 0
+}
 
-# systemd --user does not like the healthcheck command
-# disable it.
-_health=""
-if [ "$(uname)" != "Darwin" ]; then
-  _health="--health-cmd none"
-fi
+_prep_caps() {
+  _caps=""
+  _caps="${_caps} --cap-add SETGID"
+  readonly _caps
+  return 0
+}
 
-# Log the commands we use next
-# Fail on errors
-# Fail on unassigned
-set -xeu
+_prep_ports() {
+  _ports=""
 
-# Don't quote so that if user is empty it still expands
-#
-# shellcheck disable=SC2086
-exec ${_cmd} run ${_how} \
-  --name "${_name}" --hostname "${_name}" \
-  --security-opt no-new-privileges:true --cap-drop ALL \
-  --mount type=bind,source="${_mount1}",target=/app/data \
-  --net=host \
-  --cap-add SETGID \
-  ${_health} \
-  "${_image}:${_tag}" "$@"
+  # No ports
+
+  readonly _ports
+  return 0
+}
+
+_check_user() {
+  if [ "$(id -u)" -eq 0 ]; then
+    printf -- 'You must run this as a rootless container\n'
+    return 1
+  fi
+
+  _userns=""
+  # No user namespace
+  readonly _userns
+
+  return 0
+}
+
+_check_health() {
+  _health=""
+
+  # systemd does not like spawning this healthcheck
+  if [ "$(uname)" != "Darwin" ]; then
+    _health="--health-cmd none"
+  fi
+
+  readonly _health
+
+  return 0
+}
+
+_containerize() {
+  # Log the commands we use next
+  # Fail on errors
+  # Fail on unassigned
+  set -xeu
+
+  # Don't quote so that if user is empty it still expands
+  #
+  # shellcheck disable=SC2086
+  exec ${_cmd} run ${_how} \
+    --security-opt no-new-privileges:true --cap-drop ALL \
+    --net=host \
+    ${_mounts} \
+    ${_ports} \
+    ${_caps} \
+    ${_userns} \
+    ${_health} \
+    "${_image}:${_tag}" "$@"
+}
+
+main() {
+  _check_user || return 1
+  _check_health || return 1
+  _prep_mounts || return 1
+  _prep_ports || return 1
+  _prep_caps || return 1
+
+  # How do we run?
+  if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
+    shift
+    _how="-d --restart=unless-stopped"
+  else
+    _how="--rm -i -t"
+  fi
+  readonly _how
+
+  _containerize "$@" || return 1
+  return 0
+}
+
+main "$@" || exit 1
+exit 0
diff --git a/.containers/bin/video2x-upscale b/.containers/bin/video2x-upscale
--- a/.containers/bin/video2x-upscale
+++ b/.containers/bin/video2x-upscale
@@ -3,43 +3,114 @@
 readonly _image="ghcr.io/k4yt3x/video2x"
 readonly _tag="5.0.0-beta6"
 
-# Use docker or podman (priority podman)
-_cmd="sudo docker"
-if command -v podman >/dev/null; then
-  _cmd="podman"
+# Use podman, don't use docker
+readonly _cmd="podman"
+
+_prep_mounts() {
+  _mounts=""
+
+  # Bind just the working directory
+  _mounts="${_mounts} --mount type=bind,source=$(pwd),target=/host"
+
+  readonly _mounts
+  return 0
+}
+
+_prep_caps() {
+  _caps=""
+
+  # No caps
+
+  readonly _caps
+  return 0
+}
+
+_prep_ports() {
+  _ports=""
+
+  # No ports
+
+  readonly _ports
+  return 0
+}
+
+_check_user() {
+  if [ "$(id -u)" -eq 0 ]; then
+    printf -- 'You must run this as a rootless container\n'
+    return 1
+  fi
+
+  _userns=""
 
   # Need this userns option that is podman specific or we have random OCI permission error
   _userns="--userns keep-id"
-fi
-readonly _cmd
 
-# Upscale an arbitrary video using video2x container
-#
-# $1 the video file (will be output as upscaled-<NAME>)
-# $2 the target resolution (output ratio will be honored) like 720 or 1080
+  readonly _userns
 
-if [ -z "$1" ]; then
-  printf -- 'Need a target video to upscale\n'
-  exit 1
-fi
+  return 0
+}
 
-if [ -z "$2" ]; then
-  printf -- 'Need a target resolution to upscale\n'
-  exit 1
-fi
+_check_health() {
+  _health=""
+  # No healthcheck
+  readonly _health
 
-# Log the commands we use next
-# Fail on errors
-# Fail on unassigned
-set -xeu
+  return 0
+}
 
-# Don't quote so that if user is empty it still expands
-#
-# shellcheck disable=SC2086
-exec ${_cmd} run --rm \
-  --security-opt no-new-privileges:true --cap-drop ALL \
-  --device=/dev/dri \
-  --mount type=bind,source="$(pwd)",target=/host \
-  -i -t \
-  ${_userns} \
-  "${_image}:${_tag}" -i "$1" -o "upscaled-$1" -p3 upscale -h "$2" -a waifu2x -n3
+_containerize() {
+  # Log the commands we use next
+  # Fail on errors
+  # Fail on unassigned
+  set -xeu
+
+  # Don't quote so that if user is empty it still expands
+  #
+  # shellcheck disable=SC2086
+  exec ${_cmd} run ${_how} \
+    --security-opt no-new-privileges:true --cap-drop ALL \
+    --device=/dev/dri \
+    ${_mounts} \
+    ${_ports} \
+    ${_caps} \
+    ${_userns} \
+    ${_health} \
+    "${_image}:${_tag}" ${_run}
+}
+
+main() {
+  _check_user || return 1
+  _check_health || return 1
+  _prep_mounts || return 1
+  _prep_ports || return 1
+  _prep_caps || return 1
+
+  # Upscale an arbitrary video using video2x container
+  #
+  # $1 the video file (will be output as upscaled-<NAME>)
+  # $2 the target resolution (output ratio will be honored) like 720 or 1080
+
+  if [ -z "$1" ]; then
+    printf -- 'Need a target video to upscale\n'
+    return 1
+  fi
+
+  if [ -z "$2" ]; then
+    printf -- 'Need a target resolution to upscale\n'
+    return 1
+  fi
+
+  # Build command
+  readonly _run="-i $1 -o upscaled-$1 -p3 upscale -h $2 -a waifu2x -n3"
+
+  # How do we run?
+  _how="--rm -i -t"
+  readonly _how
+
+  _containerize "$@" || return 1
+  return 0
+}
+
+
+main "$@" || exit 1
+exit 0
diff --git a/dots/scripts/containers/adguardhome b/dots/scripts/containers/adguardhome
--- a/dots/scripts/containers/adguardhome
+++ b/dots/scripts/containers/adguardhome
@@ -4,73 +4,149 @@ readonly _name="adguardhome"
 readonly _image="docker.io/adguard/adguardhome"
 readonly _tag="v0.107.34"
 
-# Use docker or podman (priority podman)
-_cmd="sudo docker"
-if command -v podman >/dev/null; then
-  _cmd="podman"
-fi
-readonly _cmd
+# Use podman, don't use docker
+readonly _cmd="podman"
 
-# On MacOS we use a VM, make sure it is rootful to bind to port 53
-if [ "$(uname)" = "Darwin" ]; then
-  if [ "$(id -u)" -eq 0 ]; then
-    printf -- 'You must run this as a normal user with a rootful VM\n'
-    exit 1
+_prep_mounts() {
+  _root_path="/usr/local"
+
+  # On MacOS the VM is rootful but we run locally
+  if [ "$(uname)" = "Darwin" ]; then
+    _root_path="${HOME}/.local"
+  fi
+  readonly _root_path
+
+  readonly _mount1="${_root_path}/etc/containers/${_name}/conf"
+
+  # Prep the directories
+  mkdir -p "${_mount1}" || return 1
+
+  _mounts=""
+  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/opt/adguardhome/conf"
+
+  # For some reason, this path cannot be bound on MacOS
+  # Complains like:
+  #
+  # -> [error] auth: open DB: /opt/adguardhome/work/data/sessions.db: invalid argument
+  # -> [error] AdGuard Home cannot be initialized due to an incompatible file system.
+  if [ "$(uname)" != "Darwin" ]; then
+    readonly _mount2="${_root_path}/etc/containers/${_name}/work"
+    mkdir -p "${_mount2}" || return 1
+    _mounts="${_mounts} --mount type=bind,source=${_mount2},target=/opt/adguardhome/work"
   fi
 
-  readonly _mount1="${HOME}/.local/etc/containers/${_name}/conf"
-  readonly _mount2="${HOME}/.local/etc/containers/${_name}/work"
+  readonly _mounts
+  return 0
+}
 
-  # On MacOS we need these extra caps
-  _caps="--cap-add DAC_OVERRIDE --cap-add FOWNER"
-else
-  if [ "$(id -u)" -ne 0 ]; then
-    printf -- 'You must run this as a rootful container\n'
-    exit 1
-  fi
-
-  readonly _mount1="/usr/local/etc/containers/${_name}/conf"
-  readonly _mount2="/usr/local/etc/containers/${_name}/work"
-
-  # No extra caps on Linux
+_prep_caps() {
   _caps=""
-fi
+  _caps="${_caps} --cap-add NET_BIND_SERVICE"
 
-# Prep the directories
-mkdir -p "${_mount1}" || exit 1
-mkdir -p "${_mount2}" || exit 1
-readonly _mounts="--mount type=bind,source=${_mount1},target=/opt/adguardhome/conf \
-  --mount type=bind,source=${_mount2},target=/opt/adguardhome/work"
+  # Need these extra caps on MacOS
+  if [ "$(uname)" = "Darwin" ]; then
+    _caps="${_caps} --cap-add DAC_OVERRIDE"
+    _caps="${_caps} --cap-add FOWNER"
+  fi
 
-# Ports on Linux can use 127 syntax
-readonly _ports="-p 127.0.0.1:53:53/tcp \
-  -p 127.0.0.1:53:53/udp \
-  -p 127.0.0.1:81:81/tcp"
+  readonly _caps
+  return 0
+}
 
-readonly _caps
+_prep_ports() {
+  _ports=""
 
-# Let it daemonize
-if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
-  shift
-  _how="-d --restart=unless-stopped"
-else
-  _how="--rm"
-fi
-readonly _how
+  # MacOS doesn't like us binding to localhost only priv ports, use the general syntax and it
+  # does not complain for some rason
+  if [ "$(uname)" = "Darwin" ]; then
+    # DNS
+    _ports="${_ports} -p 53:53/tcp"
+    _ports="${_ports} -p 53:53/udp"
 
-# Log the commands we use next
-# Fail on errors
-# Fail on unassigned
-set -xeu
+    # Admin Console
+    _ports="${_ports} -p 81:81/tcp"
+  else
+    # DNS
+    _ports="${_ports} -p 127.0.0.1:53:53/tcp"
+    _ports="${_ports} -p 127.0.0.1:53:53/udp"
 
-# Don't quote so that if user is empty it still expands
-#
-# shellcheck disable=SC2086
-exec ${_cmd} run ${_how} \
-  --name "${_name}" --hostname "${_name}" \
-  --security-opt no-new-privileges:true --cap-drop ALL \
-  ${_mounts} \
-  ${_ports} \
-  ${_caps} \
-  --cap-add NET_BIND_SERVICE \
-  "${_image}:${_tag}" "$@"
+    # Admin Console
+    _ports="${_ports} -p 127.0.0.1:81:81/tcp"
+  fi
+
+  readonly _ports
+  return 0
+}
+
+_check_user() {
+  # On MacOS we use a VM, make sure it is rootful to bind to port 53
+  if [ "$(uname)" = "Darwin" ]; then
+    if [ "$(id -u)" -eq 0 ]; then
+      printf -- 'You must run this as a normal user with a rootful VM\n'
+      return 1
+    fi
+  else
+    if [ "$(id -u)" -ne 0 ]; then
+      printf -- 'You must run this as a rootful container\n'
+      return 1
+    fi
+  fi
+
+  _userns=""
+  # No user namespace
+  readonly _userns
+
+  return 0
+}
+
+_check_health() {
+  _health=""
+  # No healthcheck
+  readonly _health
+
+  return 0
+}
+
+_containerize() {
+  # Log the commands we use next
+  # Fail on errors
+  # Fail on unassigned
+  set -xeu
+
+  # Don't quote so that if user is empty it still expands
+  #
+  # shellcheck disable=SC2086
+  exec ${_cmd} run ${_how} \
+    --name "${_name}" --hostname "${_name}" \
+    --security-opt no-new-privileges:true --cap-drop ALL \
+    ${_mounts} \
+    ${_ports} \
+    ${_caps} \
+    ${_userns} \
+    ${_health} \
+    "${_image}:${_tag}" "$@"
+}
+
+main() {
+  _check_user || return 1
+  _check_health || return 1
+  _prep_mounts || return 1
+  _prep_ports || return 1
+  _prep_caps || return 1
+
+  # How do we run?
+  if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
+    shift
+    _how="-d --restart=unless-stopped"
+  else
+    _how="--rm -i -t"
+  fi
+
+  readonly _how
+
+  _containerize "$@" || return 1
+  return 0
+}
+
+main "$@" || exit 1
+exit 0
diff --git a/dots/scripts/containers/cloudflared b/dots/scripts/containers/cloudflared
--- a/dots/scripts/containers/cloudflared
+++ b/dots/scripts/containers/cloudflared
@@ -2,64 +2,130 @@
 
 readonly _name="cloudflared"
 readonly _image="docker.io/cloudflare/cloudflared"
-readonly _tag="2023.7.0"
+readonly _tag="2023.7.1"
 
-# Use docker or podman (priority podman)
-_cmd="sudo docker"
-if command -v podman >/dev/null; then
-  _cmd="podman"
-fi
-readonly _cmd
+# Use podman, don't use docker
+readonly _cmd="podman"
 
-# On MacOS we use a VM, make sure it is rootful to bind to port 53
-if [ "$(uname)" = "Darwin" ]; then
-  printf -- 'Not ready on MacOS\n'
-  exit 1
-else
-  if [ "$(id -u)" -ne 0 ]; then
-    printf -- 'You must run this as a rootful container\n'
-    exit 1
+_prep_mounts() {
+  _root_path="/usr/local"
+
+  # On MacOS the VM is rootful but we run locally
+  if [ "$(uname)" = "Darwin" ]; then
+    _root_path="${HOME}/.local"
   fi
-fi
+  readonly _root_path
 
-# Prep the directories
-readonly _mount1="/usr/local/etc/containers/${_name}/tunnel"
-mkdir -p "${_mount1}" || exit 1
+  readonly _mount1="${_root_path}/etc/containers/${_name}/tunnel"
 
-# We need DAC_OVERRIDE since the tunnel runs as non-rot
-# but our host files are owned by root
-_caps="--cap-add DAC_OVERRIDE"
+  # Prep the directories
+  mkdir -p "${_mount1}" || return 1
 
-# If no cmd args are passed, run the default tunnel
-if [ "$#" -le 0 ]; then
-  _run="tunnel run containers"
-else
-  _run="$*"
-fi
+  _mounts=""
+  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/etc/cloudflared"
+  readonly _mounts
+  return 0
+}
 
-# Let it daemonize
-if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
-  shift
-  _how="-d --restart=unless-stopped"
-else
-  _how="--rm"
-fi
-readonly _how
+_prep_caps() {
+  _caps=""
+  _caps="${_caps} --cap-add NET_BIND_SERVICE"
+  _caps="${_caps} --cap-add NET_ADMIN"
 
-# Log the commands we use next
-# Fail on errors
-# Fail on unassigned
-set -xeu
+  # Need these extra caps on MacOS
+  if [ "$(uname)" = "Darwin" ]; then
+    _caps="${_caps} --cap-add DAC_OVERRIDE"
+  fi
 
-# Don't quote so that if user is empty it still expands
-#
-# shellcheck disable=SC2086
-exec ${_cmd} run ${_how} \
-  --name "${_name}" --hostname "${_name}" \
-  --security-opt no-new-privileges:true --cap-drop ALL \
-  --mount type=bind,source=${_mount1},target=/etc/cloudflared \
-  --net=host \
-  --cap-add NET_BIND_SERVICE \
-  --cap-add NET_ADMIN \
-  ${_caps} \
-  "${_image}:${_tag}" ${_run}
+  readonly _caps
+  return 0
+}
+
+_prep_ports() {
+  _ports=""
+
+  # No ports
+
+  readonly _ports
+  return 0
+}
+
+_check_user() {
+  # On MacOS we use a VM, make sure it is rootful to bind to port 53
+  if [ "$(uname)" = "Darwin" ]; then
+    if [ "$(id -u)" -eq 0 ]; then
+      printf -- 'You must run this as a normal user with a rootful VM\n'
+      return 1
+    fi
+  else
+    if [ "$(id -u)" -ne 0 ]; then
+      printf -- 'You must run this as a rootful container\n'
+      return 1
+    fi
+  fi
+
+  _userns=""
+  # No user namespace
+  readonly _userns
+
+  return 0
+}
+
+_check_health() {
+  _health=""
+  # No healthcheck
+  readonly _health
+
+  return 0
+}
+
+_containerize() {
+  # Log the commands we use next
+  # Fail on errors
+  # Fail on unassigned
+  set -xeu
+
+  # Don't quote so that if user is empty it still expands
+  #
+  # shellcheck disable=SC2086
+  exec ${_cmd} run ${_how} \
+    --name "${_name}" --hostname "${_name}" \
+    --security-opt no-new-privileges:true --cap-drop ALL \
+    --net=host \
+    ${_mounts} \
+    ${_ports} \
+    ${_caps} \
+    ${_userns} \
+    ${_health} \
+    "${_image}:${_tag}" ${_run}
+}
+
+main() {
+  _check_user || return 1
+  _check_health || return 1
+  _prep_mounts || return 1
+  _prep_ports || return 1
+  _prep_caps || return 1
+
+  # How do we run?
+  if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
+    shift
+    _how="-d --restart=unless-stopped"
+  else
+    _how="--rm -i -t"
+  fi
+  readonly _how
+
+  # If no cmd args are passed, run the default tunnel
+  if [ "$#" -le 0 ]; then
+    _run="tunnel run containers"
+  else
+    _run="$*"
+  fi
+
+  _containerize "$@" || return 1
+  return 0
+}
+
+main "$@" || exit 1
+exit 0
