Add docker support
In theory, docker is closely API compatible with podman, or rather
podman is with docker.

So we should just be able to hunt for the right command and use it

diff --git a/.containers/bin/jellyfin b/.containers/bin/jellyfin
--- a/.containers/bin/jellyfin
+++ b/.containers/bin/jellyfin
@@ -5,7 +5,15 @@ readonly _image="docker.io/jellyfin/jellyfin"
 readonly _tag="10.10.6"
 
 # Use podman, don't use docker
-readonly _cmd="podman"
+if command -v podman >/dev/null; then
+  _cmd="podman"
+elif command -v docker >/dev/null; then
+  _cmd="docker"
+else
+  printf -- 'Requires either "podman" or "docker" ("podman" preferred)\n'
+  exit 1
+fi
+readonly _cmd
 
 _prep_mounts() {
   readonly _mount1="${HOME}/.local/etc/containers/${_name}/cache"
@@ -61,8 +69,13 @@ _check_user() {
     return 1
   fi
 
-  # Need this userns option that is podman specific or we have random OCI permission error
-  _userns="--userns keep-id"
+  # Only for podman
+  if [ "${_cmd}" = "podman" ]; then
+    # Need this userns option that is podman specific or we have random OCI permission error
+    _userns="--userns keep-id"
+  else
+    _userns=""
+  fi
   readonly _userns
 
   return 0
@@ -105,7 +118,7 @@ _containerize() {
   # MacOS can't launch with host-gateway
   # On Linux we run systemd-resolved on our host machine for DNS caching
   _network="--add-host localhost:127.0.0.1 --dns-search=."
-  if [ "$(uname)" = "Linux" ]; then
+  if [ "$(uname)" = "Linux" ] && [ "${_cmd}" = "podman" ]; then
     # Only compare the version minors
     _current_version="$("${_cmd}" --version | awk '{ print $3 }' | tr '.' ' ' | awk '{ print $1 "." $2}')"
     _is_cmd_new_enough="$(printf -- '%s' "${_current_version}" | awk '{ if ($1 >= 4.7) print 1; else print 0 }')"
@@ -159,7 +172,7 @@ main() {
 
   # Wait for the ${XDG_RUNTIME_DIR}/podman folder to be available before launching
   # This folder is created "at some point" in response to podman commands being run
-  if [ "$(uname)" = "Linux" ]; then
+  if [ "$(uname)" = "Linux" ] && [ "${_cmd}" = "podman" ]; then
     while [ ! -d "${XDG_RUNTIME_DIR}/containers" ]; do
       sleep 1 || {
         printf -- 'Cancelled while waiting for container runtime to stand up.\n'
diff --git a/dots/scripts/linux/pyamsoft-settings/hosts/all/opt/pyamsoft/bin/container-teardown b/dots/scripts/linux/pyamsoft-settings/hosts/all/opt/pyamsoft/bin/container-teardown
--- a/dots/scripts/linux/pyamsoft-settings/hosts/all/opt/pyamsoft/bin/container-teardown
+++ b/dots/scripts/linux/pyamsoft-settings/hosts/all/opt/pyamsoft/bin/container-teardown
@@ -2,6 +2,17 @@
 
 _PROG="$(basename "$0")"
 
+# Use podman, don't use docker
+if command -v podman >/dev/null; then
+  _cmd="podman"
+elif command -v docker >/dev/null; then
+  _cmd="docker"
+else
+  printf -- 'Requires either "podman" or "docker" ("podman" preferred)\n'
+  exit 1
+fi
+readonly _cmd
+
 _usage() {
   printf -- '%s\n' "$(
     cat <<EOF
@@ -32,13 +43,13 @@ _teardown_container() {
 
   # Attempt nice stop
   printf -- '[teardown] Attempt nice stop container: %s\n' "${_container}"
-  podman stop -t "${_teardown_time}" "${_container}" >/dev/null || {
+  "${_cmd}" stop -t "${_teardown_time}" "${_container}" >/dev/null || {
     printf -- '[teardown] Failed to nicely stop container %s\n' "${_container}"
   }
 
   # Remove the container
   printf -- '[teardown] Attempt force-remove container: %s\n' "${_container}"
-  podman rm -f "${_container}" >/dev/null || {
+  "${_cmd}" rm -f "${_container}" >/dev/null || {
     printf -- '[teardown] Failed to force remove the container %s\n' "${_container}"
 
     # If this fails, we failed
@@ -47,9 +58,16 @@ _teardown_container() {
 
   # Remove the network
   printf -- '[teardown] Attempt remove container network: %s\n' "${_container}"
-  podman network rm -f -t "${_teardown_time}" "${_container}" >/dev/null || {
-    printf -- '[teardown] Failed to remove the container network: %s\n' "${_container}"
-  }
+  if [ "${_cmd}" = "podman" ]; then
+    "${_cmd}" network rm -f -t "${_teardown_time}" "${_container}" >/dev/null || {
+      printf -- '[teardown] Failed to remove the container network: %s\n' "${_container}"
+    }
+  else
+    # Docker does not support -t flag for network rm
+    "${_cmd}" network rm -f "${_container}" >/dev/null || {
+      printf -- '[teardown] Failed to remove the container network: %s\n' "${_container}"
+    }
+  fi
 
   printf -- '[teardown] Container is completely torn down: %s\n\n' "${_container}"
 
@@ -91,7 +109,7 @@ _teardown_compose() {
   }
 
   printf -- '[teardown] Attempt bring down compose: %s\n' "${_container}"
-  podman compose --file "${_compose_file}" down --remove-orphans -t "${_teardown_time}" || {
+  "${_cmd}" compose --file "${_compose_file}" down --remove-orphans -t "${_teardown_time}" || {
     printf -- '[teardown] Failed to bring down compose: %s\n' "${_container}"
     return 1
   }
@@ -105,7 +123,7 @@ _teardown_compose() {
 main() {
   # Podman expects us to be in a accessible CWD
   cd "${HOME}" || {
-    printf -- '[teardown] Unable to cd to user HOME for podman usage\n'
+    printf -- '[teardown] Unable to cd to user HOME for %s usage\n' "${_cmd}"
     return 1
   }
 
diff --git a/dots/scripts/linux/pyamsoft-settings/hosts/all/opt/pyamsoft/bin/delegate-containers b/dots/scripts/linux/pyamsoft-settings/hosts/all/opt/pyamsoft/bin/delegate-containers
--- a/dots/scripts/linux/pyamsoft-settings/hosts/all/opt/pyamsoft/bin/delegate-containers
+++ b/dots/scripts/linux/pyamsoft-settings/hosts/all/opt/pyamsoft/bin/delegate-containers
@@ -3,6 +3,17 @@
 _PROG_NAME="$(basename "$0")"
 readonly _PROG_NAME
 
+# Use podman, don't use docker
+if command -v podman >/dev/null; then
+  _cmd="podman"
+elif command -v docker >/dev/null; then
+  _cmd="docker"
+else
+  printf -- 'Requires either "podman" or "docker" ("podman" preferred)\n'
+  exit 1
+fi
+readonly _cmd
+
 _dotfiles() {
   exec git --git-dir "${HOME}"/.dotfiles --work-tree "${HOME}" "$@"
 }
@@ -15,12 +26,12 @@ _usage() {
 
 <actions>
 
-[container]:   Exectue podman operations on containers
+[container]:   Exectue ${_cmd} operations on containers
 
-  ps           Runs 'podman ps', passing all arguments
-  logs         Runs 'podman logs', passing all arguments
-  images       Runs 'podman images', passing all arguments
-  inspect      Runs 'podman inspect', passing all arguments
+  ps           Runs '${_cmd} ps', passing all arguments
+  logs         Runs '${_cmd} logs', passing all arguments
+  images       Runs '${_cmd} images', passing all arguments
+  inspect      Runs '${_cmd} inspect', passing all arguments
 
 [service]:     Service management related operations
 
@@ -32,10 +43,10 @@ _usage() {
 
 [system]:      System management related operations
 
-  checkup      Runs 'podman auto-update --dry-run'
-  enter        Runs 'podman exec -it <name> /bin/sh'
-  exec         Runs 'podman exec -it <name>'
-  prune        Runs 'podman system prune -a'
+  checkup      Runs 'podman auto-update --dry-run' ("podman" ONLY)
+  enter        Runs '${_cmd} exec -it <name> /bin/sh'
+  exec         Runs '${_cmd} exec -it <name>'
+  prune        Runs '${_cmd} system prune -a'
   pull         Runs 'dotfiles pull'
   teardown     Runs 'container-teardown <name>'
 
@@ -94,7 +105,7 @@ main() {
 
   # Podman expects us to be in a accessible CWD
   cd "${HOME}" || {
-    printf -- '[delegate-containers] Unable to cd to user HOME for podman usage\n'
+    printf -- '[delegate-containers] Unable to cd to user HOME for %s usage\n' "${_cmd}"
     return 1
   }
 
@@ -104,23 +115,28 @@ main() {
 
   case "${_action}" in
   ps | logs | images | inspect)
-    exec podman "${_action}" "$@"
+    exec "${_cmd}" "${_action}" "$@"
     ;;
   checkup)
-    exec podman auto-update --dry-run "$@"
+    if [ "${_cmd}" != "podman" ]; then
+      printf -- '[delegate-containers] The "checkup" option is only supported with podman\n'
+      return 1
+    fi
+
+    exec "${_cmd}" auto-update --dry-run "$@"
     ;;
   enter)
     # Use /bin/bash if it is available, otherwise use /bin/sh if times are tough.
-    exec podman exec -i -t "$1" /bin/sh -c 'if [ -x /bin/bash ]; then exec /bin/bash; else exec /bin/sh; fi'
+    exec "${_cmd}" exec -i -t "$1" /bin/sh -c 'if [ -x /bin/bash ]; then exec /bin/bash; else exec /bin/sh; fi'
     ;;
   exec)
     _container="$1"
     shift
 
-    exec podman exec -i -t "${_container}" "$@"
+    exec "${_cmd}" exec -i -t "${_container}" "$@"
     ;;
   prune)
-    exec podman system prune -a "$@"
+    exec "${_cmd}" system prune -a "$@"
     ;;
   pull)
     _dotfiles pull "$@"
