Update

diff --git a/.containers/bin/navidrome b/.containers/bin/navidrome
--- a/.containers/bin/navidrome
+++ b/.containers/bin/navidrome
@@ -1,47 +1,28 @@
 #!/bin/sh
 
-readonly _name="samba"
-readonly _image="docker.io/crazymax/samba"
-readonly _tag="4.18.8"
+readonly _name="audiobookshelf"
+readonly _image="ghcr.io/advplyr/audiobookshelf"
+readonly _tag="2.4.4"
 
 # Use podman, don't use docker
 readonly _cmd="podman"
 
 _prep_mounts() {
-  readonly _mount1="${HOME}/.local/etc/containers/${_name}/data"
+  readonly _mount1="${HOME}/.local/etc/containers/${_name}/metadata"
   readonly _mount2="${HOME}/.local/etc/containers/${_name}/config"
-  readonly _mount3="${HOME}/.local/etc/containers/${_name}/shares"
+  readonly _mount3="${HOME}/.local/etc/containers/${_name}/media"
+  readonly _mount4="${HOME}/.local/etc/containers/${_name}/media2"
 
   mkdir -p "${_mount1}" || return 1
   mkdir -p "${_mount2}" || return 1
   mkdir -p "${_mount3}" || return 1
+  mkdir -p "${_mount4}" || return 1
 
   _mounts=""
-  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/data"
-  _mounts="${_mounts} --mount type=bind,source=${_mount3},target=/samba"
-
-  # Mount config if possible
-  if [ -f "${_mount2}/config.yml" ]; then
-    _mounts="${_mounts} --mount type=bind,source=${_mount2}/config.yml,target=/data/config.yml"
-  fi
-
-  # Mount password files if possible
-  for f in "${_mount2}/passwd".*; do
-    case "$f" in
-      *\**)
-        # No password files
-        ;;
-      *)
-        _f_name="$(basename "$f")"
-        _mounts="${_mounts} --mount type=bind,source=${f},target=/run/secrets/${_f_name}"
-        unset _f_name
-        unset _f
-        ;;
-    esac
-  done
-  unset _f_name
-  unset _f
-
+  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/metadata"
+  _mounts="${_mounts} --mount type=bind,source=${_mount2},target=/config"
+  _mounts="${_mounts} --mount type=bind,source=${_mount3},target=/media"
+  _mounts="${_mounts} --mount type=bind,source=${_mount4},target=/media2"
   readonly _mounts
   return 0
 }
@@ -49,13 +30,7 @@ _prep_mounts() {
 _prep_caps() {
   _caps=""
 
-  # For file permissions
-  _caps="${_caps} --cap-add DAC_OVERRIDE"
-  _caps="${_caps} --cap-add CHOWN"
-  _caps="${_caps} --cap-add SETGID"
-  _caps="${_caps} --cap-add SETUID"
-
-  # Server runs on port 137-139 and 445
+  # Server runs on port 80
   _caps="${_caps} --cap-add NET_BIND_SERVICE"
 
   readonly _caps
@@ -65,8 +40,7 @@ _prep_caps() {
 _prep_ports() {
   _ports=""
 
-  # More ports in runconfig.env
-  _ports="${_ports} -p 127.0.0.1:1445:445/tcp"
+  _ports="${_ports} -p 127.0.0.1:13378:80/tcp"
 
   readonly _ports
   return 0
@@ -78,17 +52,15 @@ _check_user() {
     return 1
   fi
 
-  # Run with root for samba binding but also keep-id for /var/cache/samba/msg.lock
-  _userns="--user=0:0 --userns keep-id"
-
+  # Need this userns option that is podman specific or we have random OCI permission error
+  _userns="--userns keep-id"
   readonly _userns
 
   return 0
 }
 
 _containerize() {
-  # Samba runtime config variable
-  _smb=""
+  _abs=""
 
   # Source the runtime config (so we don't have to hardcode keys)
   _runconf="${HOME}/.local/etc/containers/${_name}/runconfig.env"
@@ -114,7 +86,7 @@ _containerize() {
     --name "${_name}" --hostname "${_name}" \
     --security-opt no-new-privileges:true --cap-drop ALL \
     --init \
-    ${_smb} \
+    ${_abs} \
     ${_mounts} \
     ${_ports} \
     ${_caps} \
