Update script
Use mangohud since the env var breaks on OpenGL games

diff --git a/dots/scripts/linux/flatpak/games/gametime b/dots/scripts/linux/flatpak/games/gametime
--- a/dots/scripts/linux/flatpak/games/gametime
+++ b/dots/scripts/linux/flatpak/games/gametime
@@ -6,7 +6,7 @@ __game_environment=""
 __game_tools=""
 __env_tools=""
 
-_export_gaming_environment() {
+_prepare_env() {
   # Use single-file shader cache
   # https://www.phoronix.com/news/Mesa-Single-File-Cache
   export MESA_DISK_CACHE_SINGLE_FILE=1
@@ -196,7 +196,7 @@ _prepare_gamescope() {
   return 0
 }
 
-_game_env_vkbasalt() {
+_prepare_vkbasalt() {
   if [ -n "${GAME_VKB}" ] && [ "${GAME_VKB}" -eq 0 ]; then
     printf -- '[gametime] vkBasalt post processing: NO (GAME_VKB=%s)\n' "${GAME_VKB}"
   else
@@ -216,7 +216,7 @@ _game_env_vkbasalt() {
   return 0
 }
 
-_game_env_zink() {
+_prepare_zink() {
   if [ -n "${GAME_ZINK}" ] && [ "${GAME_ZINK}" -ne 0 ]; then
     printf -- '[gametime] Zink for OpenGL over Vulkan: YES (GAME_ZINK=%s)\n' "${GAME_ZINK}"
     # Zink OpenGL
@@ -232,26 +232,25 @@ _game_env_zink() {
   return 0
 }
 
-_game_env_mangohud() {
+_prepare_mangohud() {
   _mangohud_config="fps,frametime,cpu_temp,gpu_temp,ram,vram,swap,cpu_mhz,gpu_core_clock,gpu_mem_clock,resolution,show_fps_limit,vkbasalt,gamemode,fsr,font_size=18,width=400"
 
   if [ -n "${GAME_HUD}" ]; then
     if [ "${GAME_HUD}" -eq 0 ]; then
       printf -- '[gametime] MangoHud performance overlay: HIDDEN (GAME_HUD=%s)\n' "${GAME_HUD}"
       export MANGOHUD_CONFIG="${_mangohud_config},no_display"
-    __game_environment="${__game_environment} MANGOHUD_CONFIG=${MANGOHUD_CONFIG} MANGOHUD=1"
+      __env_tools="${__env_tools} mangohud"
     elif [ "${GAME_HUD}" -eq 1 ]; then
       printf -- '[gametime] MangoHud performance overlay: YES (GAME_HUD=%s)\n' "${GAME_HUD}"
       export MANGOHUD_CONFIG="${_mangohud_config}"
-    __game_environment="${__game_environment} MANGOHUD_CONFIG=${MANGOHUD_CONFIG} MANGOHUD=1"
+      __env_tools="${__env_tools} mangohud"
     else
       printf -- '[gametime] MangoHud performance overlay: OFF (GAME_HUD=%s)\n' "${GAME_HUD}"
-    __game_environment="${__game_environment} MANGOHUD_CONFIG=${MANGOHUD_CONFIG} MANGOHUD=0"
     fi
   else
     printf -- '[gametime] MangoHud performance overlay: HIDDEN (GAME_HUD=%s)\n' "${GAME_HUD}"
     export MANGOHUD_CONFIG="${_mangohud_config},no_display"
-    __game_environment="${__game_environment} MANGOHUD_CONFIG=${MANGOHUD_CONFIG} MANGOHUD=1"
+      __env_tools="${__env_tools} mangohud"
   fi
 
   unset _mangohud_config
@@ -259,7 +258,7 @@ _game_env_mangohud() {
 }
 
 
-_env_tool_obs() {
+_prepare_obs() {
   if ! command -v obs-gamecapture >/dev/null 2>&1; then
     printf -- '[gametime] Cannot enable OBS, not installed\n'
     return 0
@@ -283,34 +282,14 @@ _env_tool_obs() {
   unset GAME_OBS
 }
 
-_enable_env() {
-  printf -- '[gametime] Preparing host gaming environment...\n'
+_prepare() {
+  printf -- '[gametime] Preparing gaming environment...\n'
 
-  _export_gaming_environment || return 1
-
-  return 0
-}
-
-_enable_game_env() {
-  printf -- '[gametime] Preparing scoped gaming environment...\n'
-
-  _game_env_vkbasalt || return 1
-  _game_env_zink || return 1
-  _game_env_mangohud || return 1
-
-  return 0
-}
-
-_enable_env_tools() {
-  printf -- '[gametime] Preparing host tools...\n'
-
-  _env_tool_obs || return 1
-
-  return 0
-}
-
-_enable_game_tools() {
-  printf -- '[gametime] Preparing scoped tools...\n'
+  _prepare_env || return 1
+  _prepare_obs || return 1
+  _prepare_vkbasalt || return 1
+  _prepare_zink || return 1
+  _prepare_mangohud || return 1
 
   return 0
 }
@@ -354,28 +333,13 @@ main() {
     __hostname=""
   }
 
-  _enable_env || {
-    printf -- '[gametime] Unable to export gaming environment\n'
+  _prepare || {
+    printf -- '[gametime] Unable to prepare gaming environment\n'
     return 1
   }
 
   _prepare_gamescope || {
     printf -- '[gametime] Unable to prepare gamescope\n'
-    return 1
-  }
-
-  _enable_env_tools || {
-    printf -- '[gametime] Unable to setup __env_tools\n'
-    return 1
-  }
-
-  _enable_game_tools || {
-    printf -- '[gametime] Unable to setup __game_tools\n'
-    return 1
-  }
-
-  _enable_game_env || {
-    printf -- '[gametime] Unable to setup __game_environment\n'
     return 1
   }
 
