Add more tweaks for nerd1, the struggle bus

diff --git a/dots/scripts/linux/flatpak/games/gametime b/dots/scripts/linux/flatpak/games/gametime
--- a/dots/scripts/linux/flatpak/games/gametime
+++ b/dots/scripts/linux/flatpak/games/gametime
@@ -38,6 +38,17 @@ _export_gaming_environment() {
   # Disable vertical blank
   export vlank_mode=0
 
+  # nerd1 is an iGPU, we apply even more performance tweaks
+  if [ "${__hostname}" = "nerd1" ]; then
+    # https://www.basnieuwenhuizen.nl/a-first-foray-into-rendering-less/
+    # https://linux-gaming.kwindu.eu/index.php?title=Improving_performance#Minor_tweaks
+    #
+    # where we used to render 1 pixel using 1 pixel of info, we now render 2 pixels (it's like halving the resolution in a way)
+    export RADV_FORCE_VRS=2x2
+    export RADV_DEBUG=novrsflatshading
+    printf -- '[gametime] Applying nerd1 tweaks\n'
+  fi
+
   unset GAME_FIX
   return 0
 }
@@ -298,14 +309,14 @@ main() {
     return 1
   fi
 
-  _export_gaming_environment || {
-    printf -- '[gametime] Unable to export gaming environment\n'
-    return 1
-  }
-
   _get_hostname || {
     printf -- '[gametime] Unable to resolve hostname\n'
     __hostname=""
+  }
+
+  _export_gaming_environment || {
+    printf -- '[gametime] Unable to export gaming environment\n'
+    return 1
   }
 
   _prepare_gamescope || {
