Openrct2

diff --git a/dots/containers/openrct2/openrct2-dedicated b/dots/containers/openrct2/openrct2-dedicated
--- a/dots/containers/openrct2/openrct2-dedicated
+++ b/dots/containers/openrct2/openrct2-dedicated
@@ -1,26 +1,125 @@
 #!/bin/sh
 
-readonly _RCT_STORAGE="${HOME}/games/openrct2/container"
-readonly _RCT_PASSWD="poop"
+readonly _name="openrct2-server"
+readonly _image="docker.io/openrct2/openrct2-cli"
+readonly _tag="0.4.5"
 
-main() {
-  park="$1"
-  if [ -z "${park}" ]; then
-    printf -- 'Pass a path to an OpenRCT2 save game in root: %s.\n' "${_RCT_STORAGE}"
+# Use podman, don't use docker
+readonly _cmd="podman"
+
+_prep_mounts() {
+  readonly _mount1="${HOME}/.local/etc/containers/${_name}/gamefiles"
+  readonly _mount2="${HOME}/.local/etc/containers/${_name}/config"
+
+  # Prep the directories
+  mkdir -p "${_mount1}" || return 1
+  mkdir -p "${_mount2}" || return 1
+
+  _mounts=""
+  _mounts="${_mounts} --mount type=bind,source=${_mount1},target=/home/openrct2/.config/OpenRCT2"
+  _mounts="${_mounts} --mount type=bind,source=${_mount2},target=/home/openrct2/myfiles"
+
+  readonly _mounts
+  return 0
+}
+
+_prep_caps() {
+  _caps=""
+
+  readonly _caps
+  return 0
+}
+
+_prep_ports() {
+  _ports=""
+
+  _ports="${_ports} -p 127.0.0.1:11753:11753/tcp"
+  _ports="${_ports} -p 127.0.0.1:11753:11753/udp"
+
+  readonly _ports
+  return 0
+}
+
+_check_user() {
+  if [ "$(id -u)" -eq 0 ]; then
+    printf -- 'You must run this as a rootless container\n'
     return 1
   fi
 
-  printf -- 'Running dedicated openrct2 docker container for park: %s\n' "${park}"
-  exec podman run \
-    --name openrct2 --hostname openrct2 \
+  _userns="--userns keep-id"
+
+  readonly _userns
+
+  return 0
+}
+
+_check_health() {
+  _health=""
+
+  # systemd does not like spawning this healthcheck
+  if [ "$(uname)" != "Darwin" ]; then
+    _health="--health-cmd none"
+  fi
+
+  readonly _health
+
+  return 0
+}
+
+_containerize() {
+  readonly _RCT_PASSWD="poop"
+
+  # Log the commands we use next
+  # Fail on errors
+  # Fail on unassigned
+  set -xeu
+
+  # This container uses the gluetun VPN network stack.
+  # Gluetun must be running before this container.
+
+  # Don't quote so that if user is empty it still expands
+  #
+  # shellcheck disable=SC2086
+  exec ${_cmd} run ${_how} \
+    --name "${_name}" --hostname "${_name}" \
     --security-opt no-new-privileges:true --cap-drop ALL \
-    --rm -i -t\
     --init \
-    --userns keep-id \
-    --mount type=bind,source="${_RCT_STORAGE},target=/home/openrct2/.config/OpenRCT2" \
-    -p 127.0.0.1:11753:11753/tcp -p 127.0.0.1:11753:11753/udp \
-    docker.io/openrct2/openrct2-cli:latest \
-    host /home/openrct2/.config/OpenRCT2/save/"${park}" --password "${_RCT_PASSWD}"
+    ${_mounts} \
+    ${_ports} \
+    ${_caps} \
+    ${_userns} \
+    ${_health} \
+    "${_image}:${_tag}" \
+    host "/home/openrct2/.config/OpenRCT2/save/${park}" \
+    --password "${_RCT_PASSWD}"
+    "$@"
+}
+
+main() {
+  _check_user || return 1
+  _check_health || return 1
+  _prep_mounts || return 1
+  _prep_ports || return 1
+  _prep_caps || return 1
+
+  # How do we run?
+  if [ "$1" = "-d" ] || [ "$1" = "--detach" ]; then
+    shift
+    _how="-d --restart=unless-stopped"
+  else
+    _how="--rm -i -t"
+  fi
+  readonly _how
+
+  park="$1"
+  if [ -z "${park}" ]; then
+    printf -- 'Pass a path to an OpenRCT2 save game in root: %s.\n' "${_mount1}"
+    return 1
+  fi
+  shift
+
+  _containerize "$@" || return 1
+  return 0
 }
 
 main "$@" || exit 1
