Update dockerize to prepare directories as the right container user

diff --git a/scripts/dockerize/dockerize b/scripts/dockerize/dockerize
--- a/scripts/dockerize/dockerize
+++ b/scripts/dockerize/dockerize
@@ -5,6 +5,10 @@
 # As such, our container needs to run root:root in order for paths to be writable.
 IS_MACOS_MESSED_UP=1
 
+# Container user and group
+d_user=""
+d_group=""
+
 # The name of the script running. This should be a symlink from a named script, like adguardhome
 # to this script which can be generically named
 _name="$(basename "$0")"
@@ -12,23 +16,6 @@ _name="$(basename "$0")"
 # The root of docker configuration on the host machine
 _root="/usr/local/etc/docker"
 _app="${_root}/${_name}"
-
-# Run containers unprivileged but also not as our own user
-# Since a container runs as root by default that's bad, though root in a container
-# On MacOS we have a permission problem with files created in containers ignoring UID, so we instead ensure
-# docker runs as our current local user
-if [ "$(uname)" = "Darwin" ] && [ "${IS_MACOS_MESSED_UP}" -ne 0 ]; then
-  printf -- 'MacOS is buggy. Do not attempt user permission seperation.\n'
-  _user="$(id -un)"
-  _group="$(id -gn)"
-else
-  # Run every container as a dynamically created docker-* user
-  # in the dockerusers group.
-  #
-  # The real user should be a member of the dockerusers group so they can still interact with files
-  _user="docker-${_name}"
-  _group="dockerusers"
-fi
 
 ##
 # Enable bridge networking on MacOS
@@ -57,30 +44,30 @@ __linux_enable_bridge_network()
 __linux_create_docker_usergroup()
 {
   # Check that the group does not already exist
-  if ! getent group "${_group}" > /dev/null; then
-    printf -- 'Creating docker container group: %s\n' "${_group}"
+  if ! getent group "${d_group}" > /dev/null; then
+    printf -- 'Creating docker container group: %s\n' "${d_group}"
     # Create a group for docker users
-    # Assign it to the _group as primary
-    groupadd "${_group}" || {
-      printf -- 'Could not make docker group: %s\n' "${_group}"
+    # Assign it to the d_group as primary
+    groupadd "${d_group}" || {
+      printf -- 'Could not make docker group: %s\n' "${d_group}"
       return 1
     }
   fi
 
   # Check that the user does not already exist
-  if ! getent passwd "${_user}" > /dev/null; then
-    printf -- 'Creating docker container user: %s\n' "${_user}"
+  if ! getent passwd "${d_user}" > /dev/null; then
+    printf -- 'Creating docker container user: %s\n' "${d_user}"
     # Create a user with no home, and no user group.
-    # Assign it to the _group as primary
-    useradd --no-create-home --no-user-group -g "${_group}" "${_user}" || {
-      printf -- 'Could not make docker user: %s\n' "${_user}"
+    # Assign it to the d_group as primary
+    useradd --no-create-home --no-user-group -g "${d_group}" "${d_user}" || {
+      printf -- 'Could not make docker user: %s\n' "${d_user}"
       return 1
     }
   fi
 
   # Add user to group
-  gpasswd -a "${_user}" "${_group}" || {
-    printf -- 'Failed to add docker user to group %s -> %s\n' "${_user}" "${_group}"
+  gpasswd -a "${d_user}" "${d_group}" || {
+    printf -- 'Failed to add docker user to group %s -> %s\n' "${d_user}" "${d_group}"
     return 1
   }
 
@@ -98,13 +85,13 @@ __mac_create_docker_usergroup()
     printf -- 'MacOS volume mounts are messed up, do not dscl\n'
   else
     # Check that the group does not already exist
-    if ! dscl . list /groups | grep "${_group}" > /dev/null; then
+    if ! dscl . list /groups | grep "${d_group}" > /dev/null; then
       highest_gid="$(dscl . list /groups PrimaryGroupID | awk '{print $2}' | sort -n | tail -n 1)"
       new_gid="$(( highest_gid + 1 ))"
 
       # Create the group
-      dscl . create /Groups/"${_group}" || {
-        printf -- 'Failed to create /Groups/%s\n' "${_group}"
+      dscl . create /Groups/"${d_group}" || {
+        printf -- 'Failed to create /Groups/%s\n' "${d_group}"
 
         unset highest_gid
         unset new_gid
@@ -112,8 +99,8 @@ __mac_create_docker_usergroup()
       }
 
       # Assign group ID
-      dscl . create /Groups/"${_group}" gid "${new_gid}" || {
-        printf -- 'Failed to assign /Groups/%s GID: %s\n' "${_group}" "${new_gid}"
+      dscl . create /Groups/"${d_group}" gid "${new_gid}" || {
+        printf -- 'Failed to assign /Groups/%s GID: %s\n' "${d_group}" "${new_gid}"
 
         unset highest_gid
         unset new_gid
@@ -121,8 +108,8 @@ __mac_create_docker_usergroup()
       }
 
       # Assign Group name
-      dscl . create /Groups/"${_group}" RealName "Docker Users" || {
-        printf -- 'Failed to assign /Groups/%s RealName\n' "${_group}"
+      dscl . create /Groups/"${d_group}" RealName "Docker Users" || {
+        printf -- 'Failed to assign /Groups/%s RealName\n' "${d_group}"
 
         unset highest_gid
         unset new_gid
@@ -130,8 +117,8 @@ __mac_create_docker_usergroup()
       }
 
       # Assign Group passwd
-      dscl . create /Groups/"${_group}" passwd "*" || {
-        printf -- 'Failed to assign /Groups/%s passwd\n' "${_group}"
+      dscl . create /Groups/"${d_group}" passwd "*" || {
+        printf -- 'Failed to assign /Groups/%s passwd\n' "${d_group}"
 
         unset highest_gid
         unset new_gid
@@ -143,13 +130,13 @@ __mac_create_docker_usergroup()
     fi
 
     # Check that the user does not exist
-    if ! dscl . list /users | grep "${_user}" > /dev/null; then
+    if ! dscl . list /users | grep "${d_user}" > /dev/null; then
       highest_uid="$(dscl . list /users UniqueID | awk '{print $2}' | sort -n | tail -n 1)"
       new_uid="$(( highest_uid + 1 ))"
 
       # Create user
-      dscl . -create /Users/"${_user}" || {
-        printf -- 'Failed to create new user %s\n' "${_user}"
+      dscl . -create /Users/"${d_user}" || {
+        printf -- 'Failed to create new user %s\n' "${d_user}"
 
         unset highest_uid
         unset new_uid
@@ -157,27 +144,27 @@ __mac_create_docker_usergroup()
       }
 
       # Assign UID
-      dscl . -create /Users/"${_user}" UniqueID "${new_uid}"  || {
-        printf -- 'Failed to assign  user UID %s %s\n' "${_user}" "${new_uid}"
+      dscl . -create /Users/"${d_user}" UniqueID "${new_uid}"  || {
+        printf -- 'Failed to assign  user UID %s %s\n' "${d_user}" "${new_uid}"
 
         unset highest_uid
         unset new_uid
         return 1
       }
 
-      existing_group_id="$(dscl . list /groups PrimaryGroupID | grep "${_group}" | awk '{print $2}')"
+      existing_group_id="$(dscl . list /groups PrimaryGroupID | grep "${d_group}" | awk '{print $2}')"
 
-      dscl . -create /Users/"${_user}" UserShell /bin/nologin
-      dscl . -create /Users/"${_user}" RealName "Docker ${_name}"
-      dscl . -create /Users/"${_user}" PrimaryGroupID "${existing_group_id}"
+      dscl . -create /Users/"${d_user}" UserShell /bin/nologin
+      dscl . -create /Users/"${d_user}" RealName "Docker ${_name}"
+      dscl . -create /Users/"${d_user}" PrimaryGroupID "${existing_group_id}"
 
       unset highest_uid
       unset new_uid
     fi
 
     # Add user to group
-    dscl . append /Groups/"${_group}" GroupMembership "${_user}" || {
-      printf -- 'Failed to add user to group %s -> %s\n' "${_user}" "${_group}"
+    dscl . append /Groups/"${d_group}" GroupMembership "${d_user}" || {
+      printf -- 'Failed to add user to group %s -> %s\n' "${d_user}" "${d_group}"
       return 1
     }
   fi
@@ -210,7 +197,7 @@ attempt_create_container()
   }
 
   # Own the directory as the docker user
-  chown "${_user}:${_group}" "${_app}" || {
+  chown "${d_user}:${d_group}" "${_app}" || {
     printf -- 'Failed to own the host directory %s\n' "${_app}"
 
     unset create_container
@@ -273,11 +260,15 @@ CONTAINER_PORTS=""
 CONTAINER_CAPS=""
 
 # User: Override the --user option passed to the container.
-# Pass UID:GID instead of names for maximum compatibility.
-# Will be prepended with --user
-# Ex: 1000:1000 -> "--user 1000:1000"
+# Pass UID instead of names for maximum compatibility.
+# This user will be parsed into the --user=uid:gid format,
+# where the UID is the resolved UID of the provided user, and the group
+# is the user's primary Group.
+# Ex: root -> --user=0:0
+# Ex: myuser -> --user=1000:1000
+# Ex: 700 -> --user=700:700
 #
-# CONTAINER_USER="1000:1000"
+# CONTAINER_USER="1000"
 CONTAINER_USER=""
 
 # Options: Any options passed to the container raw
@@ -372,7 +363,7 @@ prepare_dirs()
     }
 
     # Own the directory as the docker user
-    chown "${_user}:${_group}" "${path_d}" || {
+    chown "${d_user}:${d_group}" "${path_d}" || {
       printf -- 'Failed to own the host directory %s\n' "${path_d}"
 
       unset d
@@ -429,7 +420,7 @@ compile_container_options()
 {
   # NOTE: Do not log anything in this function as we export the stdout as a variable
 
-  my_container_options=""
+  my_container_options="--name ${_name} --security-opt no-new-privileges --cap-drop ALL"
 
   # Volume mounts in the format {host_directory_relative}:{container_absolute}
   for d in ${CONTAINER_DIRS}; do
@@ -452,22 +443,19 @@ compile_container_options()
   done
 
   # Resolve User {user} or {user:group} or {uid} or {uid:gid}
-  if [ -n "${CONTAINER_USER}" ]; then
-    # Manual override, may not work on MacOS
-    my_container_options="${my_container_options} --user ${CONTAINER_USER}"
-  elif [ "$(uname)" = "Darwin" ] && [ "${IS_MACOS_MESSED_UP}" -ne 0 ]; then
+  if [ "$(uname)" = "Darwin" ] && [ "${IS_MACOS_MESSED_UP}" -ne 0 ]; then
     # For some reason, even volume mounts as root into docker instead of as the docker user.
     # Beacuse of this, just run docker assuming our local user on MacOS only
     # Blank it out as if we had never passed an option - will run the user as default container user or as root.
     # On MacOS, even though the container says root, files are created with the correct user and permissions.
-    #my_container_options="${my_container_options} --user ${CONTAINER_USER}"
+    #my_container_options="${my_container_options} --user $(id -u "${d_user}"):$(id -g "${d_user}")"
     true
   else
     # You must run --user with UID:GID instead of names or docker won't resolve names created on the fly.
     #
     # Failing to specify a user runs the container user as root, and files created in the container
     # are marked as created by root user 0
-    my_container_options="${my_container_options} --user $(id -u "${_user}"):$(id -g "${_user}")"
+    my_container_options="${my_container_options} --user $(id -u "${d_user}"):$(id -g "${d_user}")"
   fi
 
   # Echo out
@@ -480,7 +468,6 @@ compile_container_options()
   unset CONTAINER_PORTS
   unset CONTAINER_CAPS
   unset CONTAINER_OPTIONS
-  unset CONTAINER_USER
 
   # Don't unset CONTAINER_ARGS since we need them
   # unset CONTAINER_ARGS
@@ -528,6 +515,82 @@ create_docker_usergroup()
   return 0
 }
 
+resolve_container_user()
+{
+  if [ -z "${CONTAINER_USER}" ]; then
+    printf -- 'Prepare container with user %s:%s\n' "${d_user}" "${d_group}"
+    return 0
+  fi
+
+  printf -- 'Resolve container user from %s\n' "${CONTAINER_USER}"
+
+  # Pull out the user|uid:group|gid
+  split_user="$(printf -- '%s' "${CONTAINER_USER}" | tr ':' ' ')"
+  userlike="$(printf -- '%s' "${split_user}" | awk '{ print $1 }')"
+
+  # Need a user
+  if [ -z "${userlike}" ]; then
+    printf -- 'Missing user|uid in CONTAINER_USER: %s\n' "${CONTAINER_USER}"
+
+    unset split_user
+    unset userlike
+    unset CONTAINER_USER
+    return 1
+  fi
+
+  # Figure out the username
+  d_user="$(id -u -n "${userlike}" 2>/dev/null)"
+  if [ -z "${d_user}" ]; then
+    printf -- 'Invalid container user|uid: %s\n' "${userlike}"
+
+    unset split_user
+    unset userlike
+    unset CONTAINER_USER
+    return 1
+  fi
+
+  # Since we found a user, figure out the group too
+  d_group="$(id -g -n "${userlike}" 2>/dev/null)"
+  if [ -z "${d_group}" ]; then
+    printf -- 'Invalid container group for user: %s\n' "${d_user}"
+
+    unset split_user
+    unset userlike
+    unset CONTAINER_USER
+    return 1
+  fi
+
+  unset split_user
+  unset userlike
+  unset grouplike
+
+  # Unset global
+  unset CONTAINER_USER
+  return 1
+}
+
+init_user()
+{
+  # Run containers unprivileged but also not as our own user
+  # Since a container runs as root by default that's bad, though root in a container
+  # On MacOS we have a permission problem with files created in containers ignoring UID, so we instead ensure
+  # docker runs as our current local user
+  if [ "$(uname)" = "Darwin" ] && [ "${IS_MACOS_MESSED_UP}" -ne 0 ]; then
+    printf -- 'MacOS is buggy. Do not attempt user permission seperation.\n'
+    d_user="$(id -un)"
+    d_group="$(id -gn)"
+  else
+    # Run every container as a dynamically created docker-* user
+    # in the dockerusers group.
+    #
+    # The real user should be a member of the dockerusers group so they can still interact with files
+    d_user="docker-${_name}"
+    d_group="dockerusers"
+  fi
+
+  return 0
+}
+
 main()
 {
   # We don't need to check for root as the command will fail
@@ -542,9 +605,14 @@ main()
     return 1
   }
 
+  init_user || {
+    printf -- 'Failed to initialize user\n'
+    return 1
+  }
+
   # Create docker user and group
   create_docker_usergroup || {
-    printf -- 'Failed to create docker usergroup %s %s\n' "${_user}" "${_group}"
+    printf -- 'Failed to create docker usergroup %s %s\n' "${d_user}" "${d_group}"
     return 1
   }
 
@@ -566,6 +634,12 @@ main()
     return 1
   }
 
+  # Set the user for the following steps based on the CONTAINER_USER if possible
+  resolve_container_user || {
+    printf -- 'Could not resolve user for container %s.\n' "${_name}"
+    return 1
+  }
+
   # Prepare mounts
   if [ -n "${CONTAINER_DIRS}" ]; then
     prepare_dirs || {
@@ -577,8 +651,6 @@ main()
   # Compile all options into one
   options="$(compile_container_options)"
 
-  printf -- 'Running container %s\n' "${CONTAINER_TARGET}"
-
   if [ "$1" = "systemd" ]; then
     # Eat argument
     shift
@@ -586,28 +658,22 @@ main()
     # Then grab args
     args="$(compile_container_args "$@")"
 
+    printf -- 'Running container docker run --rm %s %s %s\n' \
+      "${options}" "${CONTAINER_TARGET}" "${args}"
+
     # Don't quote expansion - we want the raw strings
     # shellcheck disable=SC2086
-    exec docker run \
-      --name "${_name}" \
-      --init \
-      --security-opt no-new-privileges \
-      --cap-drop ALL \
-      --rm \
-      ${options} "${CONTAINER_TARGET}" ${args}
+    exec docker run --rm ${options} "${CONTAINER_TARGET}" ${args}
   else
     # Then grab args
     args="$(compile_container_args "$@")"
 
+    printf -- 'Running container docker run --restart unless-stopped -d %s %s %s\n' \
+      "${options}" "${CONTAINER_TARGET}" "${args}"
+
     # Don't quote expansion - we want the raw strings
     # shellcheck disable=SC2086
-    exec docker run \
-      --name "${_name}" \
-      --init \
-      --security-opt no-new-privileges \
-      --cap-drop ALL \
-      --restart unless-stopped -d \
-      ${options} "${CONTAINER_TARGET}" ${args}
+    exec docker run --restart unless-stopped -d ${options} "${CONTAINER_TARGET}" ${args}
    fi
 }
 
