Modify installer for vkbasalt conf

diff --git a/dots/apps/flatpak/games/installer b/dots/apps/flatpak/games/installer
--- a/dots/apps/flatpak/games/installer
+++ b/dots/apps/flatpak/games/installer
@@ -7,7 +7,9 @@
 # $2 script to install from this directory
 installer() {
   app_name="$1"
-  script="$2"
+  target="$2"
+  script="$3"
+  mark="$4"
   current_directory="$(pwd)"
 
   printf -- 'Attempt install script %s into flatpak app %s\n' "${script}" "${app_name}"
@@ -18,20 +20,27 @@ installer() {
       return 1
     }
 
-    mkdir -p .local/bin || {
-      printf -- 'Failed to create local bin directory for app: %s\n' "${app_name}"
+    mkdir -p "${target}" || {
+      printf -- 'Failed to create %s directory for app: %s\n' "${target}" "${app_name}"
       return 2
     }
 
-    cp -f "${current_directory}/$script" ".local/bin/${script}" || {
-      printf -- 'Failed to copy script %s into local bin directory for app: %s\n' "${script}" "${app_name}"
+    cp -f "${current_directory}/$script" "${target}/${script}" || {
+      printf -- 'Failed to copy script %s into %s directory for app: %s\n' "${script}" "${target}" "${app_name}"
       return 3
     }
 
-    chmod +x ".local/bin/${script}" || {
-      printf -- 'Failed to mark script %s executable for app: %s\n' "${script}" "${app_name}"
-      return 4
-    }
+    if [ "${mark}" -eq 1 ]; then
+      chmod +x "${target}/${script}" || {
+        printf -- 'Failed to mark script %s executable for app: %s\n' "${script}" "${app_name}"
+        return 4
+      }
+    else
+      chmod -x "${target}/${script}" || {
+        printf -- 'Failed to mark script %s unexecutable for app: %s\n' "${script}" "${app_name}"
+        return 4
+      }
+    fi
 
     cd "${current_directory}" || {
       printf -- 'Failed to cd out of flatpak app directory: %s back to %s\n.' "${app_name}" "${current_directory}"
@@ -41,16 +50,22 @@ installer() {
     printf -- '    %s installed for flatpak app %s\n' "${script}" "${app_name}"
 
     unset app_name
+    unset target
     unset script
+    unset mark
     unset current_directory
   fi
 
   return 0
 }
 
-installer "com.heroicgameslauncher.hgl" "gametime" || exit 1
-installer "com.valvesoftware.Steam" "gametime" || exit 1
-installer "io.openrct2.OpenRCT2" "gametime" || exit 1
+installer "com.heroicgameslauncher.hgl" ".local/bin" "gametime" 1 || exit 1
+installer "com.valvesoftware.Steam" ".local/bin" "gametime" 1 || exit 1
+installer "io.openrct2.OpenRCT2" ".local/bin" "gametime" 1 || exit 1
+
+installer "com.heroicgameslauncher.hgl" "config/vkBasalt" "vkBasalt.conf" 0 || exit 1
+installer "com.valvesoftware.Steam" "config/vkBasalt" "vkBasalt.conf" 0 || exit 1
+installer "io.openrct2.OpenRCT2" "config/vkBasalt" "vkBasalt.conf" 0 || exit 1
 
 exit 0
 
