Use amdctl to undervolt
It's slightly more reliable than the zenstates script
We keep the zenstates script around for C6 though

diff --git a/system/usr/local/bin/adjust-ryzen b/system/usr/local/bin/adjust-ryzen
--- a/system/usr/local/bin/adjust-ryzen
+++ b/system/usr/local/bin/adjust-ryzen
@@ -1,13 +1,13 @@
 #!/bin/sh
 
+# Needed for C6 disable
 readonly zenstates='/usr/local/src/Zenstates-Linux'
-readonly script="${zenstates}/zenstates.py"
 readonly url='https://github.com/irusanov/ZenStates-Linux'
-readonly gui_command="${script}"
-readonly command="${gui_command} --no-gui"
+readonly script="${zenstates}/zenstates.py"
+readonly command="${script} --no-gui"
 
-readonly voltage_undervolt="40" # 1.15000V
-readonly voltage_original="32"  # 1.23750V
+readonly voltage_undervolt="64" # 1150mV
+readonly voltage_original="50"  # 1238mV
 
 check_zenstates()
 {
@@ -51,24 +51,41 @@ require_root()
   return 0
 }
 
-load_kernel_modules()
+prepare_system()
 {
   modprobe -i msr || {
     printf -- 'Failed to load "msr" module\n'
     return 1
   }
 
-  modprobe -i cpuid || {
-    printf -- 'Failed to load "cpuid" module\n'
+  echo "on" > /sys/module/msr/parameters/allow_writes || {
+    printf -- 'Failed to configure "msr" module to allow writes\n'
     return 1
   }
 
   return 0
 }
 
+disable_c6() {
+  printf -- 'Disable C6 to prevent system hangs...\n'
+
+  # shellcheck disable=SC2086
+  ${command} --c6-disable > /dev/null || return 1
+
+  return 0
+}
+
 main()
 {
-  enable="$1"
+  cmd="$1"
+  option="$2"
+
+  dry=""
+  if [ "${option}" = "--dry" ]; then
+    dry="-t"
+  else
+    dry=""
+  fi
 
   # Pre-req user
   require_root || return 1
@@ -76,32 +93,31 @@ main()
   # Pre-req software
   require 'git' || return 1
   require 'python3' || return 1
+  require 'amdctl' || return 1
 
   # Pre-req script location
   check_zenstates || return 1
 
+  # Prepare system for MSR writing
+  prepare_system || return 1
+
   # Run the script and disable c6
-  load_kernel_modules || return 1
+  disable_c6 || return 1
 
-  # shellcheck disable=SC2086
-  ${command} --c6-disable || return 1
-
-  if [ "${enable}" = "list" ]; then
-    # shellcheck disable=SC2086
-    exec ${command} -l || return 1
-  elif [ "${enable}" = "gui" ]; then
-    # shellcheck disable=SC2086
-    exec ${gui_command} || return 1
-  elif [ "${enable}" = "enable" ]; then
+  if [ "${cmd}" = "list" ]; then
+    exec amdctl -g || return 1
+  elif [ "${cmd}" = "enable" ]; then
     # Apply p-state undervolt
-    # shellcheck disable=SC2086
-    exec ${command} -p 0 -v "${voltage_undervolt}" || return 1
-  elif [ "${enable}" = "disable" ]; then
+    amdctl "${dry}" -p 0 -v "${voltage_undervolt}" > /dev/null || return 1
+    printf -- 'Undervolted to VID: %s\n' "${voltage_undervolt}"
+  elif [ "${cmd}" = "disable" ]; then
     # Restore default p-state
-    # shellcheck disable=SC2086
-    exec ${command} -p 0 -v "${voltage_original}" || return 1
+    amdctl "${dry}" -p 0 -v "${voltage_original}" > /dev/null || return 1
+    printf -- 'Restored original voltage at VID: %s\n' "${voltage_original}"
   else
-    printf -- 'Call with "list" "gui" "enable" "disable"\n'
+    printf -- '\n'
+    printf -- 'Call with "list" "enable" "disable"\n'
+    printf -- '    Can optionall pass option --dry for a dry-run.\n'
     return 1
   fi
 }
