Don't apply other stuff

diff --git a/system/usr/local/bin/adjust-ryzen b/system/usr/local/bin/adjust-ryzen
--- a/system/usr/local/bin/adjust-ryzen
+++ b/system/usr/local/bin/adjust-ryzen
@@ -51,17 +51,28 @@ require_root()
   return 0
 }
 
-load_kernel_modules()
+prepare_system()
 {
+  printf -- 'Load MSR module and allow writes...\n'
+
   modprobe -i msr || {
     printf -- 'Failed to load "msr" module\n'
     return 1
   }
 
-  modprobe -i cpuid || {
-    printf -- 'Failed to load "cpuid" module\n'
+  echo "on" > /sys/module/msr/parameters/allow_writes || {
+    printf -- 'Failed to enable writes on "msr" module\n'
     return 1
   }
+
+  return 0
+}
+
+disable_c6() {
+  printf -- 'Disable C6 to prevent system hangs...\n'
+
+  # shellcheck disable=SC2086
+  ${command} --c6-disable > /dev/null || return 1
 
   return 0
 }
@@ -80,11 +91,11 @@ main()
   # Pre-req script location
   check_zenstates || return 1
 
-  # Run the script and disable c6
-  load_kernel_modules || return 1
+  # Prepare system
+  prepare_system || return 1
 
-  # shellcheck disable=SC2086
-  ${command} --c6-disable || return 1
+  # Run the script and disable c6
+  disable_c6 || return 1
 
   if [ "${enable}" = "list" ]; then
     # shellcheck disable=SC2086
