Split up for MacOS

diff --git a/system/usr/local/bin/docker-container b/system/usr/local/bin/docker-container
--- a/system/usr/local/bin/docker-container
+++ b/system/usr/local/bin/docker-container
@@ -5,25 +5,29 @@
 # As such, our container needs to run root:root in order for paths to be writable.
 IS_MACOS_MESSED_UP=1
 
+# The name of the script running. This should be a symlink from a named script, like adguardhome
+# to this script which can be generically named
 _name="$(basename "$0")"
 
+# The root of docker configuration on the host machine
 _root="/usr/local/etc/docker"
 _app="${_root}/${_name}"
 
 # Run containers unprivileged but also not as our own user
 # Since a container runs as root by default that's bad, though root in a container
-# is still safer than real root. Run every container as a dynamically created docker-* user
-# in the dockerusers group.
-#
-# The real user should be a member of the dockerusers group so they can still interact with files
-_user="docker-${_name}"
-_group="dockerusers"
-
-# Volume mounts are broken on MacOS, don't make a dockeruser, just use our own
+# On MacOS we have a permission problem with files created in containers ignoring UID, so we instead ensure
+# docker runs as our current local user
 if [ "$(uname)" = "Darwin" ] && [ "${IS_MACOS_MESSED_UP}" -ne 0 ]; then
   printf -- 'MacOS is buggy. Do not attempt user permission seperation.\n'
   _user="$(id -un)"
   _group="$(id -gn)"
+else
+  # Run every container as a dynamically created docker-* user
+  # in the dockerusers group.
+  #
+  # The real user should be a member of the dockerusers group so they can still interact with files
+  _user="docker-${_name}"
+  _group="dockerusers"
 fi
 
 ##
@@ -83,6 +87,7 @@ attempt_create_container()
 # CONTAINER_DIRS
 # CONTAINER_PORTS
 # CONTAINER_CAPS
+# CONTAINER_USER
 # CONTAINER_OPTIONS
 # CONTAINER_ARGS
 
@@ -101,6 +106,11 @@ CONTAINER_PORTS=""
 # Capabilities: Format like --cap-add (these are only added, everything is DROPPED by default)
 # CONTAINER_CAPS="NET_BIND_SERVICE NET_ADMIN"
 CONTAINER_CAPS=""
+
+# User: Override the --user option passed to the container.
+# Pass UID:GID instead of names for maximum compatibility.
+# CONTAINER_USER="1000:1000"
+CONTAINER_USER=""
 
 # Options: Any options passed to the container raw
 # CONTAINER_OPTIONS="-i -t --read-only"
@@ -215,21 +225,40 @@ prepare_dirs()
 }
 
 ##
+# Enable bridge networking on MacOS
+__mac_enable_bridge_network()
+{
+  printf -- 'MacOS enables bridge networking through VM implementation\n'
+  return 0
+}
+
+##
+# Enable bridge networking on Linux
+__linux_enable_bridge_network()
+{
+  # Enable IP forwarding for container bridge networking
+  printf -- 'Enable IPv4 forwarding for bridge networking\n'
+  sysctl -q -w net.ipv4.ip_forward=1 || {
+    printf -- 'Failed to enable IPv4 forwarding\n'
+    return 1
+  }
+
+  return 0
+}
+
+##
 # Setup container networking
 #
 enable_bridge_network()
 {
   # If we are running on MacOS, this sysctl won't work
-  if [ "$(uname)" != "Darwin" ]; then
-    if command -v sysctl > /dev/null; then
-      # Enable IP forwarding for container bridge networking
-      printf -- 'Enable IPv4 forwarding for bridge networking\n'
-      sysctl -q -w net.ipv4.ip_forward=1 || {
-        printf -- 'Failed to enable IPv4 forwarding\n'
-        return 1
-      }
-    fi
+  if [ "$(uname)" = "Darwin" ]; then
+    __mac_enable_bridge_network || return 1
+  else
+    __linux_enable_bridge_network || return 1
   fi
+
+  return 0
 }
 
 ##
@@ -283,6 +312,9 @@ compile_container_options()
 
   # Don't unset CONTAINER_ARGS since we need them
   # unset CONTAINER_ARGS
+  #
+  # Don't unset CONTAINER_USER since we need them
+  # unset CONTAINER_USER
   
   return 0
 }
@@ -315,108 +347,186 @@ compile_container_args()
 }
 
 ##
-# Creates a docker user and group for safer container access
-create_docker_usergroup()
+# Creates a docker user and group for safer container access on Linux
+__linux_create_docker_usergroup()
 {
-  if [ "$(uname)" != "Darwin" ]; then
-    # Linux specific
+  # Check that the group does not already exist
+  if ! getent group "${_group}" > /dev/null; then
+    printf -- 'Creating docker container group: %s\n' "${_group}"
+    # Create a group for docker users
+    # Assign it to the _group as primary
+    groupadd "${_group}" || {
+      printf -- 'Could not make docker group: %s\n' "${_group}"
+      return 1
+    }
+  fi
 
+  # Check that the user does not already exist
+  if ! getent passwd "${_user}" > /dev/null; then
+    printf -- 'Creating docker container user: %s\n' "${_user}"
+    # Create a user with no home, and no user group.
+    # Assign it to the _group as primary
+    useradd --no-create-home --no-user-group -g "${_group}" "${_user}" || {
+      printf -- 'Could not make docker user: %s\n' "${_user}"
+      return 1
+    }
+  fi
+
+  # Add user to group
+  gpasswd -a "${_user}" "${_group}" || {
+    printf -- 'Failed to add docker user to group %s -> %s\n' "${_user}" "${_group}"
+    return 1
+  }
+
+  return 0
+}
+
+##
+# Creates a docker user and group for safer container access on MacOS
+#
+# May not do anything since MacOS is buggy with user permissions
+__mac_create_docker_usergroup()
+{
+  if [ "${IS_MACOS_MESSED_UP}" -ne 0 ]; then
+    # MacOS volume mounting UID permission is messed up, don't do it
+    printf -- 'MacOS volume mounts are messed up, do not dscl\n'
+  else
     # Check that the group does not already exist
-    if ! getent group "${_group}" > /dev/null; then
-      printf -- 'Creating docker container group: %s\n' "${_group}"
-      # Create a group for docker users
-      # Assign it to the _group as primary
-      groupadd "${_group}" || {
-        printf -- 'Could not make docker group: %s\n' "${_group}"
+    if ! dscl . list /groups | grep "${_group}" > /dev/null; then
+      highest_gid="$(dscl . list /groups PrimaryGroupID | awk '{print $2}' | sort -n | tail -n 1)"
+      new_gid="$(( highest_gid + 1 ))"
+
+      # Create the group
+      dscl . create /Groups/"${_group}" || {
+        printf -- 'Failed to create /Groups/%s\n' "${_group}"
+
+        unset highest_gid
+        unset new_gid
         return 1
       }
+
+      # Assign group ID
+      dscl . create /Groups/"${_group}" gid "${new_gid}" || {
+        printf -- 'Failed to assign /Groups/%s GID: %s\n' "${_group}" "${new_gid}"
+
+        unset highest_gid
+        unset new_gid
+        return 1
+      }
+
+      # Assign Group name
+      dscl . create /Groups/"${_group}" RealName "Docker Users" || {
+        printf -- 'Failed to assign /Groups/%s RealName\n' "${_group}"
+
+        unset highest_gid
+        unset new_gid
+        return 1
+      }
+
+      # Assign Group passwd
+      dscl . create /Groups/"${_group}" passwd "*" || {
+        printf -- 'Failed to assign /Groups/%s passwd\n' "${_group}"
+
+        unset highest_gid
+        unset new_gid
+        return 1
+      }
+
+      unset highest_gid
+      unset new_gid
     fi
 
-    # Check that the user does not already exist
-    if ! getent passwd "${_user}" > /dev/null; then
-      printf -- 'Creating docker container user: %s\n' "${_user}"
-      # Create a user with no home, and no user group.
-      # Assign it to the _group as primary
-      useradd --no-create-home --no-user-group -g "${_group}" "${_user}" || {
-        printf -- 'Could not make docker user: %s\n' "${_user}"
+    # Check that the user does not exist
+    if ! dscl . list /users | grep "${_user}" > /dev/null; then
+      highest_uid="$(dscl . list /users UniqueID | awk '{print $2}' | sort -n | tail -n 1)"
+      new_uid="$(( highest_uid + 1 ))"
+
+      # Create user
+      dscl . -create /Users/"${_user}" || {
+        printf -- 'Failed to create new user %s\n' "${_user}"
+
+        unset highest_uid
+        unset new_uid
         return 1
       }
+
+      # Assign UID
+      dscl . -create /Users/"${_user}" UniqueID "${new_uid}"  || {
+        printf -- 'Failed to assign  user UID %s %s\n' "${_user}" "${new_uid}"
+
+        unset highest_uid
+        unset new_uid
+        return 1
+      }
+
+      existing_group_id="$(dscl . list /groups PrimaryGroupID | grep "${_group}" | awk '{print $2}')"
+
+      dscl . -create /Users/"${_user}" UserShell /bin/nologin
+      dscl . -create /Users/"${_user}" RealName "Docker ${_name}"
+      dscl . -create /Users/"${_user}" PrimaryGroupID "${existing_group_id}"
+
+      unset highest_uid
+      unset new_uid
     fi
 
     # Add user to group
-    gpasswd -a "${_user}" "${_group}" || {
-      printf -- 'Failed to add docker user to group %s -> %s\n' "${_user}" "${_group}"
+    dscl . append /Groups/"${_group}" GroupMembership "${_user}" || {
+      printf -- 'Failed to add user to group %s -> %s\n' "${_user}" "${_group}"
       return 1
     }
-  else
-    # MacOS specific
-    if [ "${IS_MACOS_MESSED_UP}" -ne 0 ]; then
-      # MacOS volume mounting UID permission is messed up, don't do it
-      printf -- 'MacOS volume mounts are messed up, do not dscl\n'
-    else
-      # Check that the group does not already exist
-      if ! dscl . list /groups | grep "${_group}" > /dev/null; then
-        highest_gid="$(dscl . list /groups PrimaryGroupID | awk '{print $2}' | sort -n | tail -n 1)"
-        new_gid="$(( highest_gid + 1 ))"
-
-        # Create the group
-        dscl . create /Groups/"${_group}" || {
-          printf -- 'Failed to create /Groups/%s\n' "${_group}"
-          return 1
-        }
-
-        # Assign group ID
-        dscl . create /Groups/"${_group}" gid "${new_gid}" || {
-          printf -- 'Failed to assign /Groups/%s GID: %s\n' "${_group}" "${new_gid}"
-          return 1
-        }
-
-        # Assign Group name
-        dscl . create /Groups/"${_group}" RealName "Docker Users" || {
-          printf -- 'Failed to assign /Groups/%s RealName\n' "${_group}"
-          return 1
-        }
-
-        # Assign Group passwd
-        dscl . create /Groups/"${_group}" passwd "*" || {
-          printf -- 'Failed to assign /Groups/%s passwd\n' "${_group}"
-          return 1
-        }
-      fi
-
-      # Check that the user does not exist
-      if ! dscl . list /users | grep "${_user}" > /dev/null; then
-        highest_uid="$(dscl . list /users UniqueID | awk '{print $2}' | sort -n | tail -n 1)"
-        new_uid="$(( highest_uid + 1 ))"
-
-        # Create user
-        dscl . -create /Users/"${_user}" || {
-          printf -- 'Failed to create new user %s\n' "${_user}"
-          return 1
-        }
-
-        # Assign UID
-        dscl . -create /Users/"${_user}" UniqueID "${new_uid}"  || {
-          printf -- 'Failed to assign  user UID %s %s\n' "${_user}" "${new_uid}"
-          return 1
-        }
-
-        existing_group_id="$(dscl . list /groups PrimaryGroupID | grep "${_group}" | awk '{print $2}')"
-
-        dscl . -create /Users/"${_user}" UserShell /bin/nologin
-        dscl . -create /Users/"${_user}" RealName "Docker ${_name}"
-        dscl . -create /Users/"${_user}" PrimaryGroupID "${existing_group_id}"
-      fi
-
-      # Add user to group
-      dscl . append /Groups/"${_group}" GroupMembership "${_user}" || {
-        printf -- 'Failed to add user to group %s -> %s\n' "${_user}" "${_group}"
-        return 1
-      }
-    fi
   fi
 
-  printf -- 'Running container as docker user: %s %s\n' "${_user}" "${_group}"
+  return 0
+}
+
+##
+# Creates a docker user and group for safer container access
+create_docker_usergroup()
+{
+  if [ "$(uname)" = "Darwin" ]; then
+    __mac_create_docker_usergroup || return 1
+  else
+    __linux_create_docker_usergroup || return 1
+  fi
+
+  return 0
+}
+
+##
+# Decide the --user that the container will run as
+resolve_container_user()
+{
+  my_container_user=""
+
+  # For some reason, even volume mounts as root into docker instead of as the docker user.
+  # Beacuse of this, just run docker assuming our local user on MacOS only
+  if [ -n "${CONTAINER_USER}" ]; then
+    printf -- 'Container overrides --user: %s\n' "${CONTAINER_USER}"
+
+    # Manual override, may not work on MacOS
+    my_container_user="${CONTAINER_USER}"
+  elif [ "$(uname)" = "Darwin" ] && [ "${IS_MACOS_MESSED_UP}" -ne 0 ]; then
+    printf -- 'MacOS is buggy. Do not attempt user permission seperation.\n'
+
+    # Blank it out as if we had never passed an option - will run the user as default container user or as root.
+    # On MacOS, even though the container says root, files are created with the correct user and permissions.
+    my_container_user=""
+  else
+    # You must run --user with UID:GID instead of names or docker won't resolve names created on the fly.
+    #
+    # Failing to specify a user runs the container user as root, and files created in the container
+    # are marked as created by root user 0
+    my_container_user="$(id -u "${_user}"):$(id -g "${_user}")"
+  fi
+
+  # Echo out
+  printf -- '%s' "${my_container_user}"
+
+  unset my_container_user
+
+  # Unset environment
+  unset CONTAINER_USER
+
   return 0
 }
 
@@ -468,17 +578,9 @@ main()
 
   # Compile all options into one
   options="$(compile_container_options)"
+  docker_user="$(resolve_container_user)"
 
-
-  # For some reason, even volume mounts as root into docker instead of as the docker user.
-  # Beacuse of this, just run docker assuming our local user on MacOS only
-  if [ "$(uname)" = "Darwin" ] && [ "${IS_MACOS_MESSED_UP}" -ne 0 ]; then
-    printf -- 'MacOS is buggy. Do not attempt user permission seperation.\n'
-    docker_user=""
-  else
-    # You must run --user with UID:GID instead of names or docker won't resolve names created on the fly.
-    docker_user="$(id -u "${_user}"):$(id -g "${_user}")"
-  fi
+  printf -- 'Running container %s as user: %s\n' "${CONTAINER_TARGET}" "${docker_user}"
 
   if [ "$1" = "systemd" ]; then
     # Eat argument
@@ -500,8 +602,6 @@ main()
   else
     # Then grab args
     args="$(compile_container_args "$@")"
-
-    # You must run --user with UID:GID instead of names or docker won't resolve names created on the fly.
 
     # Don't quote expansion - we want the raw strings
     # shellcheck disable=SC2086
