New gaming scripts

diff --git a/dots/scripts/gaming/gamer/setup b/dots/scripts/gaming/gamer/setup
--- a/dots/scripts/gaming/gamer/setup
+++ b/dots/scripts/gaming/gamer/setup
@@ -9,6 +9,28 @@ _check_user() {
   return 0
 }
 
+_install_launcher() {
+  printf -- '%s' "$(cat <<EOF
+#!/bin/sh
+
+if [ "${GAMER_GAMESCOPE}" -ne 0 ]; then
+  exec gametime ${_cmd} "\$@"
+else
+  exec "${_cmd}" "\$@"
+fi
+EOF
+)" | sudo tee -a /home/"${_target_user}"/bin/launcher >/dev/null || {
+  printf -- 'Failed to install launcher for user %s\n' "${_target_user}"
+  return 1
+}
+
+  # Mark exec
+  sudo chmod 700 /home/"${_target_user}"/bin/launcher || {
+    printf -- 'Failed to exec-mark launcher for user %s\n' "${_target_user}"
+    return 1
+  }
+}
+
 _create_user() {
   printf -- 'Create target user: %s\n' "${_target_user}"
   sudo useradd --create-home --shell /bin/bash --user-group "${_target_user}" || {
@@ -16,6 +38,7 @@ _create_user() {
     return 1
   }
 
+  sudo mkdir -p /home/"${_target_user}"/bin
   sudo mkdir -p /home/"${_target_user}"/.cache
   sudo mkdir -p /home/"${_target_user}"/.config
   sudo mkdir -p /home/"${_target_user}"/.local/share
@@ -29,6 +52,8 @@ _create_user() {
     printf -- 'Failed to install bash_profile for %s\n' "${_target_user}"
     return 1
   }
+
+  _install_launcher || return 1
 
   # Update access perms
   sudo chown "${_target_user}:${_target_user}" -R /home/"${_target_user}" || {
@@ -63,7 +88,10 @@ main() {
     printf -- 'Need a target user to setup!\n'
     return 1
   fi
+
+  _cmd="${_target_user}"
   _target_user="gaming-${_target_user}"
+  readonly _cmd
   readonly _target_user
 
   if ! _check_user; then
