Clean up gamer scripts
Fix the portal breaking by exporting the machinectl environment
defined by `gamelaunch` to the launched environment defined by `launcher`

diff --git a/dots/scripts/linux/gaming/gamer/gamelaunch b/dots/scripts/linux/gaming/gamer/gamelaunch
--- a/dots/scripts/linux/gaming/gamer/gamelaunch
+++ b/dots/scripts/linux/gaming/gamer/gamelaunch
@@ -3,43 +3,47 @@
 # Privileged script, to be used with gamer script and sudoers set up
 
 _check_user() {
-  if ! id -u "${_target_user}" >/dev/null 2>&1; then
-    printf -- 'Target user %s does not exist!\n' "${_target_user}"
+  _check_me="$1"
+  if ! id -u "${_check_me}" >/dev/null 2>&1; then
+    printf -- '[gamelaunch] Target user %s does not exist!\n' "${_check_me}"
+
+    unset _check_me
     return 1
   fi
 
+  unset _check_me
   return 0
 }
 
 main() {
   if [ -z "${SUDO_USER}" ]; then
-    printf -- "gamelaunch requires that you run as a regular user with sudo\n"
+    printf -- "[gamelaunch] Requires that you run as a regular user with sudo\n"
     return 1
   fi
 
   if [ "${SUDO_UID}" -eq 0 ]; then
-    printf -- "gamelaunch requires that you run as a regular user with sudo\n"
+    printf -- "[gamelaunch] Requires that you run as a regular user with sudo\n"
     return 1
   fi
 
   if [ "$(id -u)" -ne 0 ]; then
-    printf -- "gamelaunch requires that you run with sudo\n"
+    printf -- "[gamelaunch] Requires that you run with sudo\n"
     return 1
   fi
 
   if [ -z "${DISPLAY}" ]; then
-    printf -- "gamelaunch requires a valid \$DISPLAY variable.\n"
+    printf -- "[gamelaunch] Requires a valid \$DISPLAY variable.\n"
     return 1
   fi
 
   if [ -z "${XAUTHORITY}" ]; then
-    printf -- "gamelaunch requires a valid \$XAUTHORITY variable.\n"
+    printf -- "[gamelaunch] Requires a valid \$XAUTHORITY variable.\n"
     return 1
   fi
 
   _target_user="$1"
   if [ -z "${_target_user}" ]; then
-    printf -- 'gamelaunch requires a target user as the first argument\n'
+    printf -- '[gamelaunch] Requires a target user as the first argument\n'
     return 1
   fi
 
@@ -49,7 +53,7 @@ main() {
   case "$1" in
     --gamescope)
       if [ -z "$2" ]; then
-        printf -- 'Missing required --gamescope argument value!\n'
+        printf -- '[gamelaunch] Missing required --gamescope argument value!\n'
         return 1
       fi
 
@@ -63,7 +67,7 @@ main() {
     --gamescope=*)
       _split="$(printf -- '%s\n' "$1" | tr '=' ' ' | awk '{ print $2 }')"
       if [ -z "${_split}" ]; then
-        printf -- 'Missing required --gamescope= argument value!\n'
+        printf -- '[gamelaunch] Missing required --gamescope= argument value!\n'
         return 1
       fi
 
@@ -78,10 +82,16 @@ main() {
       ;;
   esac
 
-  readonly _target_user="gaming-${_target_user}"
-  if ! _check_user; then
+  _real_user="gaming-${_target_user}"
+  if ! _check_user "${_real_user}"; then
     return 1
   fi
+
+  printf -- '[gamelaunch] Running command as target user: [%s]"~/bin/launcher %s"\n' "${_real_user}" "$*"
+  printf -- '[gamelaunch] DISPLAY=%s\n' "${DISPLAY}"
+  printf -- '[gamelaunch] XAUTHORITY=%s\n' "${XAUTHORITY}"
+  printf -- '[gamelaunch] GAMER_GAMESCOPE=%s\n' "${GAMER_GAMESCOPE:-0}"
+  printf -- '[gamelaunch] GAMER=1\n'
 
   # Running machinectl shell gives us a "clean session to work with" that attaches to it's own systemctl --user session
   # and loginctl session
@@ -97,16 +107,8 @@ main() {
     --setenv="DISPLAY=${DISPLAY}" --setenv="XAUTHORITY=${XAUTHORITY}" \
     --setenv="GAMER_GAMESCOPE=${GAMER_GAMESCOPE:-0}" \
     --setenv="GAMER=1" \
-    shell "${_target_user}@.host" \
+    shell "${_real_user}@.host" \
     /bin/bash -l -c '~/bin/launcher' "$@"
-
-  # Currently, we "access" the systemd bus by manually setting the path in .bash_profile (gaming-bash_profile)
-  # and "starting" the session via loginctl lingering. It's not perfect but it works.
-  # sudo \
-  #   -u "${_target_user}" \
-  #   -i \
-  #   -- \
-  #   env GAMER_GAMESCOPE="${GAMER_GAMESCOPE:-0}" launcher "$@"
 }
 
 main "$@" || exit 1
diff --git a/dots/scripts/linux/gaming/gamer/gamer b/dots/scripts/linux/gaming/gamer/gamer
--- a/dots/scripts/linux/gaming/gamer/gamer
+++ b/dots/scripts/linux/gaming/gamer/gamer
@@ -6,37 +6,25 @@
 readonly _SCRIPT_NAME="gamer"
 
 _check_user() {
-  if ! id -u "${_target_user}" >/dev/null 2>&1; then
-    printf -- 'Target user %s does not exist!\n' "${_target_user}"
+  _check_me="$1"
+  if ! id -u "${_check_me}" >/dev/null 2>&1; then
+    printf -- '[gamer] Target user %s does not exist!\n' "${_check_me}"
+
+    unset _check_me
     return 1
   fi
 
+  unset _check_me
   return 0
 }
 
-main() {
-  _cmd="$1"
-  if [ -z "${_cmd}" ]; then
-    _cur_name=$(basename "$0")
-    readonly _cur_name
-    if [ "${_cur_name}" != "${_SCRIPT_NAME}" ]; then
-      _cmd="${_cur_name}"
-    else
-      printf -- 'Must specify a command to run as %s\n' "${_target_user}"
-      return 1
-    fi
-  else
-    shift
-  fi
+_prepare() {
+  _prepare_user="$1"
 
-  readonly _target_user="gaming-${_cmd}"
-  if ! _check_user; then
-    return 1
-  fi
+  xhost +SI:localuser:"${_prepare_user}" || {
+    printf -- '[gamer] Failed to grant xhost access to %s\n' "${_prepare_user}"
 
-  # Run
-  xhost +SI:localuser:"${_target_user}" || {
-    printf -- 'Failed to grant xhost access to %s\n' "${_target_user}"
+    unset _prepare_user
     return 1
   }
 
@@ -44,27 +32,78 @@ main() {
   _pa_mod="module-native-protocol-tcp"
   if ! pactl list modules | grep -q "${_pa_mod}"; then
     pactl load-module "${_pa_mod}" "listen=127.0.0.1" "port=4712" || {
-      printf -- 'Failed to load pactl TCP protocol\n'
+      printf -- '[gamer] Failed to load pactl TCP protocol\n'
+
+      unset _prepare_user
+      unset _pa_mod
       return 1
     }
   fi
 
+  unset _prepare_user
+  unset _pa_mod
+  return 0
+}
+
+_after() {
+  _after_user="$1"
+
+  # Then when it finishes, we make sure to clean up
+  xhost -SI:localuser:"${_after_user}" || {
+    printf -- '[gamer] Failed to revoke xhost access to %s\n' "${_after_user}"
+  }
+
+  # Do not "clean up" the pactl module for TCP, since we
+  # may not be the final one dropping off the pactl connection.
+  #
+  # Cleaning up the TCP module would kill all other sound
+
+  unset _after_user
+  return 0
+}
+
+main() {
+  _cmd="$1"
+
+  # We may have a command manually passed in.
+  # If we do not, check the name of the script we are executing as.
+  # If the script is not the actual script, then use our aliased
+  # name as the command executable.
+  #
+  # For example, symlinking this script to my-game will pass "my-game" as _cmd
+  if [ -z "${_cmd}" ]; then
+    _cur_name=$(basename "$0")
+    readonly _cur_name
+    if [ "${_cur_name}" != "${_SCRIPT_NAME}" ]; then
+      _cmd="${_cur_name}"
+    else
+      printf -- '[gamer] Must specify a command to run as!\n'
+      return 1
+    fi
+  else
+    shift
+  fi
+
+  _target_user="gaming-${_cmd}"
+  if ! _check_user "${_target_user}"; then
+    return 1
+  fi
+
+  # Run
+  _prepare "${_target_user}" || return 1
+
+  # Do all the setup and teardown as a "normal" user.
+  # The only thing gamelaunch should do as a sudo script
+  # is call machinectl to open a systemd connected user session as
+  # the _target_user
+  #
   # See gamelaunch script in /usr/local/sbin
   sudo /usr/local/sbin/gamelaunch "${_cmd}" "$@"
 
-  # Currently, we "access" the systemd bus by manually setting the path in .bash_profile (gaming-bash_profile)
-  # and "starting" the session via loginctl lingering. It's not perfect but it works.
-  # sudo \
-  #   -u "${_target_user}" \
-  #   -i \
-  #   -- \
-  #   env GAMER_GAMESCOPE="${GAMER_GAMESCOPE:-0}" launcher "$@"
+  # Clean up after
+  _after "${_target_user}" || return 1
 
-  # Then when it finishes, we make sure to clean up
-  xhost -SI:localuser:"${_target_user}" || {
-    printf -- 'Failed to revoke xhost access to %s\n' "${_target_user}"
-  }
-
+  unset _target_user
   return 0
 }
 
