Remove only if it was not made before
Existing empty files are not touched

diff --git a/.bww/bin/nvim b/.bww/bin/nvim
--- a/.bww/bin/nvim
+++ b/.bww/bin/nvim
@@ -48,18 +48,30 @@ for f in "$@"; do
       ;;
   esac
 
+  # If the file does not already exist, it is a candidate for removing later
+  _rm_later=0
+  if [ ! -f "${_full_path}" ]; then
+    _rm_later=1
+  fi
+
   # Ensure the file exists (in case we are making a new file)
   touch "${_full_path}" && {
     _filename="$(basename -- "${_full_path}")"
     _rel_jail_path="bind-$(cat /proc/sys/kernel/random/uuid)-${_filename}"
     _jail_path="${HOME}/${_rel_jail_path}"
+
     _options="${_options} --bind ${_full_path} ${_jail_path}"
     _files="${_files} ${_jail_path}"
     _jail_files="${_jail_files} ${_rel_jail_path}"
-    _rm_files="${_rm_files} ${_full_path}"
+
+    if [ "${_rm_later}" -eq 1 ]; then
+      _rm_files="${_rm_files} ${_full_path}"
+    fi
   }
 
+  unset _rm_later
   unset _filename
+  unset _rel_jail_path
   unset _jail_path
   unset _full_path
   unset f
@@ -70,13 +82,23 @@ done
 bww ${_options} ${_mounts} "${command_name}" ${_cmd_opt} -c "${HOME}/.local/bin/lvim ${_files}"
 _res="$?"
 
-# Clean up
+# Clean up jail files (they are now empty in the host system)
 for f in ${_jail_files}; do
   ff="${HOME}/.local/etc/bubblewrap/nvim/home/$f"
   rm -f "${ff}" || { 
     printf -- 'Failed to clean up bound file: %s\n' "$ff"
   }
   unset ff
+  unset f
+done
+
+# Clean up
+for f in ${_rm_files}; do
+  if file "$f" | grep -q '^.*: empty$'; then
+  rm -f "$f" || { 
+    printf -- 'Failed to clean up empty file: %s\n' "$f"
+  }
+  fi
   unset f
 done
 
