Format and fixes

diff --git a/.config/bash/aliases b/.config/bash/aliases
--- a/.config/bash/aliases
+++ b/.config/bash/aliases
@@ -11,25 +11,25 @@ for script in "${HOME}"/.bash_aliases.d/* "${XDG_CONFIG_HOME}"/bash/aliases.d/*;
   # shellcheck disable=SC1090
   [ -r "${script}" ] && {
     case "${script}" in
-      *.linux)
-        if [ "${os}" = "Linux" ]; then
-          . "${script}" || {
-            printf -- 'Linux bash_alias setup script failed: %s\n' "${script}"
-          }
-        fi
-        ;;
-      *.macos)
-        if [ "${os}" = "Darwin" ]; then
-          . "${script}" || {
-            printf -- 'MacOS bash_alias setup script failed: %s\n' "${script}"
-          }
-        fi
-        ;;
-      *)
+    *.linux)
+      if [ "${os}" = "Linux" ]; then
         . "${script}" || {
-          printf -- 'bash_alias setup script failed: %s\n' "${script}"
+          printf -- 'Linux bash_alias setup script failed: %s\n' "${script}"
         }
-        ;;
+      fi
+      ;;
+    *.macos)
+      if [ "${os}" = "Darwin" ]; then
+        . "${script}" || {
+          printf -- 'MacOS bash_alias setup script failed: %s\n' "${script}"
+        }
+      fi
+      ;;
+    *)
+      . "${script}" || {
+        printf -- 'bash_alias setup script failed: %s\n' "${script}"
+      }
+      ;;
     esac
   }
   unset script
diff --git a/.config/bash/rc b/.config/bash/rc
--- a/.config/bash/rc
+++ b/.config/bash/rc
@@ -14,25 +14,25 @@ for script in "${HOME}"/.bashrc.d/* "${XDG_CONFIG_HOME}"/bash/rc.d/*; do
   # shellcheck disable=SC1090
   [ -r "${script}" ] && {
     case "${script}" in
-      *.linux)
-        if [ "${os}" = "Linux" ]; then
-          . "${script}" || {
-            printf -- 'Linux bashrc setup script failed: %s\n' "${script}"
-          }
-        fi
-        ;;
-      *.macos)
-        if [ "${os}" = "Darwin" ]; then
-          . "${script}" || {
-            printf -- 'MacOS bashrc setup script failed: %s\n' "${script}"
-          }
-        fi
-        ;;
-      *)
+    *.linux)
+      if [ "${os}" = "Linux" ]; then
         . "${script}" || {
-            printf -- 'bashrc setup script failed: %s\n' "${script}"
+          printf -- 'Linux bashrc setup script failed: %s\n' "${script}"
         }
-        ;;
+      fi
+      ;;
+    *.macos)
+      if [ "${os}" = "Darwin" ]; then
+        . "${script}" || {
+          printf -- 'MacOS bashrc setup script failed: %s\n' "${script}"
+        }
+      fi
+      ;;
+    *)
+      . "${script}" || {
+        printf -- 'bashrc setup script failed: %s\n' "${script}"
+      }
+      ;;
     esac
   }
   unset script
