Always pass CONFIG_DIR and OS to shell setup scripts
Avoids needing each script to resolve these common variables

diff --git a/.config/bash/aliases b/.config/bash/aliases
--- a/.config/bash/aliases
+++ b/.config/bash/aliases
@@ -1,39 +1,52 @@
 # shellcheck shell=bash
 
-os="$(uname)"
+# Arguments always provided as:
+#
+# $1 - CONFIG_DIR
+# $2 - OS
 
-for script in "${HOME}"/.bash_aliases.d/* "${XDG_CONFIG_HOME}"/bash/aliases.d/*; do
-  # Sometimes os can get unset. Reset it here
-  if [ -z "${os}" ]; then
-    os="$(uname)"
-  fi
+if [ -z "$1" ]; then
+  # shellcheck disable=SC2016
+  printf -- 'Cannot source bash/aliases without providing CONFIG_DIR as $1: %s\n' "$*"
+  return 1
+fi
 
+if [ -z "$2" ]; then
+  # shellcheck disable=SC2016
+  printf -- 'Cannot source bash/aliases without providing OS as $2: %s\n' "$*"
+  return 1
+fi
+
+_cfg="$1"
+_os="$2"
+
+for _alias in "${HOME}"/.bash_aliases.d/* "${_cfg}"/bash/aliases.d/*; do
   # shellcheck disable=SC1090
-  [ -r "${script}" ] && {
-    case "${script}" in
+  [ -r "${_alias}" ] && {
+    case "${_alias}" in
     *.linux)
-      if [ "${os}" = "Linux" ]; then
-        . "${script}" || {
-          printf -- 'Linux bash_alias setup script failed: %s\n' "${script}"
+      if [ "${_os}" = "Linux" ]; then
+        . "${_alias}" || {
+          printf -- 'Linux bash/aliases setup script failed: %s args=%s\n' "${_alias}" "$*"
         }
       fi
       ;;
     *.macos)
-      if [ "${os}" = "Darwin" ]; then
-        . "${script}" || {
-          printf -- 'MacOS bash_alias setup script failed: %s\n' "${script}"
+      if [ "${_os}" = "Darwin" ]; then
+        . "${_alias}" || {
+          printf -- 'MacOS bash/aliases setup script failed: %s args=%s\n' "${_alias}" "$*"
         }
       fi
       ;;
     *)
-      . "${script}" || {
-        printf -- 'bash_alias setup script failed: %s\n' "${script}"
+      . "${_alias}" || {
+        printf -- 'bash/aliases setup script failed: %s args=%s\n' "${_alias}" "$*"
       }
       ;;
     esac
   }
-  unset script
+  unset _alias
 done
-unset script
+unset _alias
 
-unset os
+return 0
diff --git a/.config/bash/functions b/.config/bash/functions
--- a/.config/bash/functions
+++ b/.config/bash/functions
@@ -1,39 +1,52 @@
 # shellcheck shell=bash
 
-os="$(uname)"
+# Arguments always provided as:
+#
+# $1 - CONFIG_DIR
+# $2 - OS
 
-for script in "${HOME}"/.bash_functions.d/* "${XDG_CONFIG_HOME}"/bash/functions.d/*; do
-  # Sometimes os can get unset. Reset it here
-  if [ -z "${os}" ]; then
-    os="$(uname)"
-  fi
+if [ -z "$1" ]; then
+  # shellcheck disable=SC2016
+  printf -- 'Cannot source bash/functions without providing CONFIG_DIR as $1: %s\n' "$*"
+  return 1
+fi
 
+if [ -z "$2" ]; then
+  # shellcheck disable=SC2016
+  printf -- 'Cannot source bash/functions without providing OS as $2: %s\n' "$*"
+  return 1
+fi
+
+_cfg="$1"
+_os="$2"
+
+for _func in "${HOME}"/.bash_functions.d/* "${_cfg}"/bash/functions.d/*; do
   # shellcheck disable=SC1090
-  [ -r "${script}" ] && {
-    case "${script}" in
+  [ -r "${_func}" ] && {
+    case "${_func}" in
     *.linux)
-      if [ "${os}" = "Linux" ]; then
-        . "${script}" || {
-          printf -- 'Linux bash_function setup script failed: %s\n' "${script}"
+      if [ "${_os}" = "Linux" ]; then
+        . "${_func}" || {
+          printf -- 'Linux bash/functions setup script failed: %s args=%s\n' "${_func}" "$*"
         }
       fi
       ;;
     *.macos)
-      if [ "${os}" = "Darwin" ]; then
-        . "${script}" || {
-          printf -- 'MacOS bash_function setup script failed: %s\n' "${script}"
+      if [ "${_os}" = "Darwin" ]; then
+        . "${_func}" || {
+          printf -- 'MacOS bash/functions setup script failed: %s args=%s\n' "${_func}" "$*"
         }
       fi
       ;;
     *)
-      . "${script}" || {
-        printf -- 'bash_function setup script failed: %s\n' "${script}"
+      . "${_func}" || {
+        printf -- 'bash/functions setup script failed: %s args=%s\n' "${_func}" "$*"
       }
       ;;
     esac
   }
-  unset script
+  unset _func
 done
-unset script
+unset _func
 
-unset os
+return 0
diff --git a/.config/bash/profile b/.config/bash/profile
--- a/.config/bash/profile
+++ b/.config/bash/profile
@@ -1,46 +1,58 @@
 # shellcheck shell=bash
 
+# Arguments always provided as:
+#
+# $1 - CONFIG_DIR
+# $2 - OS
+
+if [ -z "$1" ]; then
+  # shellcheck disable=SC2016
+  printf -- 'Cannot source bash/profile without providing CONFIG_DIR as $1: %s\n' "$*"
+  return 1
+fi
+
+if [ -z "$2" ]; then
+  # shellcheck disable=SC2016
+  printf -- 'Cannot source bash/profile without providing OS as $2: %s\n' "$*"
+  return 1
+fi
+
+_cfg="$1"
+_os="$2"
+
 # Source if the environment is not setup
 if [ -z "${PYAMSOFT_ENVIRONMENT}" ]; then
   # shellcheck disable=SC1091
-  [ -f "${HOME}"/.pyamsoft ] && . "${HOME}"/.pyamsoft
+  [ -f "${HOME}"/.pyamsoft ] && . "${HOME}"/.pyamsoft "$@"
 fi
 
-os="$(uname)"
-
-for script in "${HOME}"/.bash_profile.d/* "${XDG_CONFIG_HOME}"/bash/profile.d/*; do
-  # Sometimes os can get unset. Reset it here
-  if [ -z "${os}" ]; then
-    os="$(uname)"
-  fi
-
+for _profile in "${HOME}"/.bash_profile.d/* "${_cfg}"/bash/profile.d/*; do
   # shellcheck disable=SC1090
-  [ -r "${script}" ] && {
-    case "${script}" in
+  [ -r "${_profile}" ] && {
+    case "${_profile}" in
     *.linux)
-      if [ "${os}" = "Linux" ]; then
-        . "${script}" || {
-          printf -- 'Linux bash_profile setup script failed: %s\n' "${script}"
+      if [ "${_os}" = "Linux" ]; then
+        . "${_profile}" || {
+          printf -- 'Linux bash/profile setup script failed: %s args=%s\n' "${_profile}" "$*"
         }
       fi
       ;;
     *.macos)
-      if [ "${os}" = "Darwin" ]; then
-        . "${script}" || {
-          printf -- 'MacOS bash_profile setup script failed: %s\n' "${script}"
+      if [ "${_os}" = "Darwin" ]; then
+        . "${_profile}" || {
+          printf -- 'MacOS bash/profile setup script failed: %s args=%s\n' "${_profile}" "$*"
         }
       fi
       ;;
     *)
-      . "${script}" || {
-        printf -- 'bash_profile setup script failed: %s\n' "${script}"
+      . "${_profile}" || {
+        printf -- 'bash/profile setup script failed: %s args=%s\n' "${_profile}" "$*"
       }
       ;;
     esac
   }
-  unset script
+  unset _profile
 done
-unset script
+unset _profile
 
-unset os
 return 0
diff --git a/.config/bash/rc b/.config/bash/rc
--- a/.config/bash/rc
+++ b/.config/bash/rc
@@ -1,42 +1,55 @@
 # shellcheck shell=bash
 
+# Arguments always provided as:
+#
+# $1 - CONFIG_DIR
+# $2 - OS
+
 # If not running interactively, don't do anything
 [[ "$-" != *i* ]] && return
 
-os="$(uname)"
+if [ -z "$1" ]; then
+  # shellcheck disable=SC2016
+  printf -- 'Cannot source bash/rc without providing CONFIG_DIR as $1: %s\n' "$*"
+  return 1
+fi
 
-for script in "${HOME}"/.bashrc.d/* "${XDG_CONFIG_HOME}"/bash/rc.d/*; do
-  # Sometimes os can get unset. Reset it here
-  if [ -z "${os}" ]; then
-    os="$(uname)"
-  fi
+if [ -z "$2" ]; then
+  # shellcheck disable=SC2016
+  printf -- 'Cannot source bash/rc without providing OS as $2: %s\n' "$*"
+  return 1
+fi
 
+_cfg="$1"
+_os="$2"
+
+for _rc in "${HOME}"/.bashrc.d/* "${_cfg}"/bash/rc.d/*; do
   # shellcheck disable=SC1090
-  [ -r "${script}" ] && {
-    case "${script}" in
+  [ -r "${_rc}" ] && {
+    case "${_rc}" in
     *.linux)
-      if [ "${os}" = "Linux" ]; then
-        . "${script}" || {
-          printf -- 'Linux bashrc setup script failed: %s\n' "${script}"
+      if [ "${_os}" = "Linux" ]; then
+        . "${_rc}" || {
+          printf -- 'Linux bash/rc setup script failed: %s args=%s\n' "${_rc}" "$*"
         }
       fi
       ;;
     *.macos)
-      if [ "${os}" = "Darwin" ]; then
-        . "${script}" || {
-          printf -- 'MacOS bashrc setup script failed: %s\n' "${script}"
+      if [ "${_os}" = "Darwin" ]; then
+        . "${_rc}" || {
+          printf -- 'MacOS bash/rc setup script failed: %s args=%s\n' "${_rc}" "$*"
         }
       fi
       ;;
     *)
-      . "${script}" || {
-        printf -- 'bashrc setup script failed: %s\n' "${script}"
+      . "${_rc}" || {
+        printf -- 'bash/rc setup script failed: %s args=%s\n' "${_rc}" "$*"
       }
       ;;
     esac
   }
-  unset script
+  unset _rc
 done
-unset script
+unset _rc
 
-unset os
+return 0
