Source from local.d and tracked .d folder in collated order

diff --git a/.config/bash/aliases b/.config/bash/aliases
--- a/.config/bash/aliases
+++ b/.config/bash/aliases
@@ -20,33 +20,56 @@ fi
 _cfg="$1"
 _os="$2"
 
+_all_alias=""
 for _alias in "${HOME}"/.bash_aliases.d/* "${_cfg}"/bash/aliases.d/* "${_cfg}"/bash/aliases.local.d/*; do
-  # shellcheck disable=SC1090
-  [ -r "${_alias}" ] && {
-    case "${_alias}" in
-    *.linux)
-      if [ "${_os}" = "Linux" ]; then
-        . "${_alias}" || {
-          printf -- 'Linux bash/aliases setup script failed: %s args=%s\n' "${_alias}" "$*"
-        }
-      fi
-      ;;
-    *.macos)
-      if [ "${_os}" = "Darwin" ]; then
-        . "${_alias}" || {
-          printf -- 'MacOS bash/aliases setup script failed: %s args=%s\n' "${_alias}" "$*"
-        }
-      fi
-      ;;
-    *)
-      . "${_alias}" || {
-        printf -- 'bash/aliases setup script failed: %s args=%s\n' "${_alias}" "$*"
-      }
-      ;;
-    esac
-  }
+  if [ -r "${_alias}" ]; then
+    if [ -z "${_all_alias}" ]; then
+      _all_alias="${_alias}"
+    else
+      _all_alias="${_alias}
+${_all_alias}"
+    fi
+  fi
   unset _alias
 done
 unset _alias
+
+_old_ifs="${IFS}"
+_new_ifs='
+'
+
+IFS="${_new_ifs}"
+for _alias in $(printf -- '%s' "${_all_alias}" | awk '{ base=$0; sub(".*/", "", base); printf "%s\t%s\n", base, $0; }' | LC_COLLATE=C sort -t $'\t' -k 1,1 -k 2,2 | cut -f2-); do
+  IFS="${_old_ifs}"
+  case "${_alias}" in
+  *.linux)
+    if [ "${_os}" = "Linux" ]; then
+      # shellcheck disable=SC1090
+      . "${_alias}" || {
+        printf -- 'Linux bash/rc setup script failed: %s args=%s\n' "${_alias}" "$*"
+      }
+    fi
+    ;;
+  *.macos)
+    if [ "${_os}" = "Darwin" ]; then
+      # shellcheck disable=SC1090
+      . "${_alias}" || {
+        printf -- 'MacOS bash/rc setup script failed: %s args=%s\n' "${_alias}" "$*"
+      }
+    fi
+    ;;
+  *)
+    # shellcheck disable=SC1090
+    . "${_alias}" || {
+      printf -- 'bash/rc setup script failed: %s args=%s\n' "${_alias}" "$*"
+    }
+    ;;
+  esac
+  IFS="${_new_ifs}"
+  unset _alias
+done
+unset _alias
+unset _all_alias
+IFS="${_old_ifs}"
 
 return 0
diff --git a/.config/bash/completion b/.config/bash/completion
--- a/.config/bash/completion
+++ b/.config/bash/completion
@@ -5,36 +5,62 @@
 # Look for additional files in $<current-directory>/completions.d
 _self_directory="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
 
+if [ -z "${_os}" ]; then
+  _os="$(uname)"
+fi
+
+_all_bcomp=""
 for _bcomp in "${_self_directory}"/completions.d/* "${_self_directory}"/completions.local.d/*; do
-  # shellcheck disable=SC1090
-  [ -r "${_bcomp}" ] && {
-    case "${_bcomp}" in
-    *.linux)
-      if [ "${_os}" = "Linux" ]; then
-        . "${_bcomp}" || {
-          printf -- 'Linux bash/completion setup script failed: %s args=%s\n' "${_bcomp}" "$*"
-        }
-      fi
-      ;;
-    *.macos)
-      if [ "${_os}" = "Darwin" ]; then
-        . "${_bcomp}" || {
-          printf -- 'MacOS bash/completion setup script failed: %s args=%s\n' "${_bcomp}" "$*"
-        }
-      fi
-      ;;
-    *)
-      . "${_bcomp}" || {
-        printf -- 'bash/completion setup script failed: %s args=%s\n' "${_bcomp}" "$*"
-      }
-      ;;
-    esac
-  }
+  if [ -r "${_bcomp}" ]; then
+    if [ -z "${_all_bcomp}" ]; then
+      _all_bcomp="${_bcomp}"
+    else
+      _all_bcomp="${_bcomp}
+${_all_bcomp}"
+    fi
+  fi
   unset _bcomp
 done
 unset _bcomp
 
+_old_ifs="${IFS}"
+_new_ifs='
+'
+
+IFS="${_new_ifs}"
+for _bcomp in $(printf -- '%s' "${_all_bcomp}" | awk '{ base=$0; sub(".*/", "", base); printf "%s\t%s\n", base, $0; }' | LC_COLLATE=C sort -t $'\t' -k 1,1 -k 2,2 | cut -f2-); do
+  IFS="${_old_ifs}"
+  case "${_bcomp}" in
+  *.linux)
+    if [ "${_os}" = "Linux" ]; then
+      # shellcheck disable=SC1090
+      . "${_bcomp}" || {
+        printf -- 'Linux bash/rc setup script failed: %s args=%s\n' "${_bcomp}" "$*"
+      }
+    fi
+    ;;
+  *.macos)
+    if [ "${_os}" = "Darwin" ]; then
+      # shellcheck disable=SC1090
+      . "${_bcomp}" || {
+        printf -- 'MacOS bash/rc setup script failed: %s args=%s\n' "${_bcomp}" "$*"
+      }
+    fi
+    ;;
+  *)
+    # shellcheck disable=SC1090
+    . "${_bcomp}" || {
+      printf -- 'bash/rc setup script failed: %s args=%s\n' "${_bcomp}" "$*"
+    }
+    ;;
+  esac
+  IFS="${_new_ifs}"
+  unset _bcomp
+done
+unset _bcomp
+unset _all_bcomp
+IFS="${_old_ifs}"
+
 unset _self_directory
 
 return 0
-
diff --git a/.config/bash/functions b/.config/bash/functions
--- a/.config/bash/functions
+++ b/.config/bash/functions
@@ -20,33 +20,56 @@ fi
 _cfg="$1"
 _os="$2"
 
+_all_func=""
 for _func in "${HOME}"/.bash_functions.d/* "${_cfg}"/bash/functions.d/* "${_cfg}"/bash/functions.local.d/*; do
-  # shellcheck disable=SC1090
-  [ -r "${_func}" ] && {
-    case "${_func}" in
-    *.linux)
-      if [ "${_os}" = "Linux" ]; then
-        . "${_func}" || {
-          printf -- 'Linux bash/functions setup script failed: %s args=%s\n' "${_func}" "$*"
-        }
-      fi
-      ;;
-    *.macos)
-      if [ "${_os}" = "Darwin" ]; then
-        . "${_func}" || {
-          printf -- 'MacOS bash/functions setup script failed: %s args=%s\n' "${_func}" "$*"
-        }
-      fi
-      ;;
-    *)
-      . "${_func}" || {
-        printf -- 'bash/functions setup script failed: %s args=%s\n' "${_func}" "$*"
-      }
-      ;;
-    esac
-  }
+  if [ -r "${_func}" ]; then
+    if [ -z "${_all_func}" ]; then
+      _all_func="${_func}"
+    else
+      _all_func="${_func}
+${_all_func}"
+    fi
+  fi
   unset _func
 done
 unset _func
+
+_old_ifs="${IFS}"
+_new_ifs='
+'
+
+IFS="${_new_ifs}"
+for _func in $(printf -- '%s' "${_all_func}" | awk '{ base=$0; sub(".*/", "", base); printf "%s\t%s\n", base, $0; }' | LC_COLLATE=C sort -t $'\t' -k 1,1 -k 2,2 | cut -f2-); do
+  IFS="${_old_ifs}"
+  case "${_func}" in
+  *.linux)
+    if [ "${_os}" = "Linux" ]; then
+      # shellcheck disable=SC1090
+      . "${_func}" || {
+        printf -- 'Linux bash/rc setup script failed: %s args=%s\n' "${_func}" "$*"
+      }
+    fi
+    ;;
+  *.macos)
+    if [ "${_os}" = "Darwin" ]; then
+      # shellcheck disable=SC1090
+      . "${_func}" || {
+        printf -- 'MacOS bash/rc setup script failed: %s args=%s\n' "${_func}" "$*"
+      }
+    fi
+    ;;
+  *)
+    # shellcheck disable=SC1090
+    . "${_func}" || {
+      printf -- 'bash/rc setup script failed: %s args=%s\n' "${_func}" "$*"
+    }
+    ;;
+  esac
+  IFS="${_new_ifs}"
+  unset _func
+done
+unset _func
+unset _all_func
+IFS="${_old_ifs}"
 
 return 0
diff --git a/.config/bash/profile b/.config/bash/profile
--- a/.config/bash/profile
+++ b/.config/bash/profile
@@ -26,33 +26,56 @@ if [ -z "${PYAMSOFT_ENVIRONMENT}" ]; then
   [ -f "${HOME}"/.pyamsoft ] && . "${HOME}"/.pyamsoft "$@"
 fi
 
+_all_profile=""
 for _profile in "${HOME}"/.bash_profile.d/* "${_cfg}"/bash/profile.d/* "${_cfg}"/bash/profile.local.d/*; do
-  # shellcheck disable=SC1090
-  [ -r "${_profile}" ] && {
-    case "${_profile}" in
-    *.linux)
-      if [ "${_os}" = "Linux" ]; then
-        . "${_profile}" || {
-          printf -- 'Linux bash/profile setup script failed: %s args=%s\n' "${_profile}" "$*"
-        }
-      fi
-      ;;
-    *.macos)
-      if [ "${_os}" = "Darwin" ]; then
-        . "${_profile}" || {
-          printf -- 'MacOS bash/profile setup script failed: %s args=%s\n' "${_profile}" "$*"
-        }
-      fi
-      ;;
-    *)
-      . "${_profile}" || {
-        printf -- 'bash/profile setup script failed: %s args=%s\n' "${_profile}" "$*"
-      }
-      ;;
-    esac
-  }
+  if [ -r "${_profile}" ]; then
+    if [ -z "${_all_profile}" ]; then
+      _all_profile="${_profile}"
+    else
+      _all_profile="${_profile}
+${_all_profile}"
+    fi
+  fi
   unset _profile
 done
 unset _profile
+
+_old_ifs="${IFS}"
+_new_ifs='
+'
+
+IFS="${_new_ifs}"
+for _profile in $(printf -- '%s' "${_all_profile}" | awk '{ base=$0; sub(".*/", "", base); printf "%s\t%s\n", base, $0; }' | LC_COLLATE=C sort -t $'\t' -k 1,1 -k 2,2 | cut -f2-); do
+  IFS="${_old_ifs}"
+  case "${_profile}" in
+  *.linux)
+    if [ "${_os}" = "Linux" ]; then
+      # shellcheck disable=SC1090
+      . "${_profile}" || {
+        printf -- 'Linux bash/rc setup script failed: %s args=%s\n' "${_profile}" "$*"
+      }
+    fi
+    ;;
+  *.macos)
+    if [ "${_os}" = "Darwin" ]; then
+      # shellcheck disable=SC1090
+      . "${_profile}" || {
+        printf -- 'MacOS bash/rc setup script failed: %s args=%s\n' "${_profile}" "$*"
+      }
+    fi
+    ;;
+  *)
+    # shellcheck disable=SC1090
+    . "${_profile}" || {
+      printf -- 'bash/rc setup script failed: %s args=%s\n' "${_profile}" "$*"
+    }
+    ;;
+  esac
+  IFS="${_new_ifs}"
+  unset _profile
+done
+unset _profile
+unset _all_profile
+IFS="${_old_ifs}"
 
 return 0
diff --git a/.config/bash/rc b/.config/bash/rc
--- a/.config/bash/rc
+++ b/.config/bash/rc
@@ -23,33 +23,56 @@ fi
 _cfg="$1"
 _os="$2"
 
+_all_rc=""
 for _rc in "${HOME}"/.bashrc.d/* "${_cfg}"/bash/rc.d/* "${_cfg}"/bash/rc.local.d/*; do
-  # shellcheck disable=SC1090
-  [ -r "${_rc}" ] && {
-    case "${_rc}" in
-    *.linux)
-      if [ "${_os}" = "Linux" ]; then
-        . "${_rc}" || {
-          printf -- 'Linux bash/rc setup script failed: %s args=%s\n' "${_rc}" "$*"
-        }
-      fi
-      ;;
-    *.macos)
-      if [ "${_os}" = "Darwin" ]; then
-        . "${_rc}" || {
-          printf -- 'MacOS bash/rc setup script failed: %s args=%s\n' "${_rc}" "$*"
-        }
-      fi
-      ;;
-    *)
-      . "${_rc}" || {
-        printf -- 'bash/rc setup script failed: %s args=%s\n' "${_rc}" "$*"
-      }
-      ;;
-    esac
-  }
+  if [ -r "${_rc}" ]; then
+    if [ -z "${_all_rc}" ]; then
+      _all_rc="${_rc}"
+    else
+      _all_rc="${_rc}
+${_all_rc}"
+    fi
+  fi
   unset _rc
 done
 unset _rc
+
+_old_ifs="${IFS}"
+_new_ifs='
+'
+
+IFS="${_new_ifs}"
+for _rc in $(printf -- '%s' "${_all_rc}" | awk '{ base=$0; sub(".*/", "", base); printf "%s\t%s\n", base, $0; }' | LC_COLLATE=C sort -t $'\t' -k 1,1 -k 2,2 | cut -f2-); do
+  IFS="${_old_ifs}"
+  case "${_rc}" in
+  *.linux)
+    if [ "${_os}" = "Linux" ]; then
+      # shellcheck disable=SC1090
+      . "${_rc}" || {
+        printf -- 'Linux bash/rc setup script failed: %s args=%s\n' "${_rc}" "$*"
+      }
+    fi
+    ;;
+  *.macos)
+    if [ "${_os}" = "Darwin" ]; then
+      # shellcheck disable=SC1090
+      . "${_rc}" || {
+        printf -- 'MacOS bash/rc setup script failed: %s args=%s\n' "${_rc}" "$*"
+      }
+    fi
+    ;;
+  *)
+    # shellcheck disable=SC1090
+    . "${_rc}" || {
+      printf -- 'bash/rc setup script failed: %s args=%s\n' "${_rc}" "$*"
+    }
+    ;;
+  esac
+  IFS="${_new_ifs}"
+  unset _rc
+done
+unset _rc
+unset _all_rc
+IFS="${_old_ifs}"
 
 return 0
