Capture and log errors during setup

diff --git a/.config/bash/profile b/.config/bash/profile
--- a/.config/bash/profile
+++ b/.config/bash/profile
@@ -14,16 +14,22 @@ for script in "${HOME}"/.bash_profile.d/* "${XDG_CONFIG_HOME}"/bash/profile.d/*;
     case "${script}" in
       *.linux)
         if [ "${os}" = "Linux" ]; then
-          . "${script}"
+          . "${script}" || {
+            printf -- 'Linux bash_profile setup script failed: %s\n' "${script}"
+          }
         fi
         ;;
       *.macos)
         if [ "${os}" = "Darwin" ]; then
-          . "${script}"
+          . "${script}" || {
+            printf -- 'MacOS bash_profile setup script failed: %s\n' "${script}"
+          }
         fi
         ;;
       *)
-        . "${script}"
+        . "${script}" || {
+            printf -- 'bash_profile setup script failed: %s\n' "${script}"
+        }
         ;;
     esac
   }
diff --git a/.config/bash/rc b/.config/bash/rc
--- a/.config/bash/rc
+++ b/.config/bash/rc
@@ -11,16 +11,22 @@ for script in "${HOME}"/.bashrc.d/* "${XDG_CONFIG_HOME}"/bash/rc.d/*; do
     case "${script}" in
       *.linux)
         if [ "${os}" = "Linux" ]; then
-          . "${script}"
+          . "${script}" || {
+            printf -- 'Linux bashrc setup script failed: %s\n' "${script}"
+          }
         fi
         ;;
       *.macos)
         if [ "${os}" = "Darwin" ]; then
-          . "${script}"
+          . "${script}" || {
+            printf -- 'MacOS bashrc setup script failed: %s\n' "${script}"
+          }
         fi
         ;;
       *)
-        . "${script}"
+        . "${script}" || {
+            printf -- 'bashrc setup script failed: %s\n' "${script}"
+        }
         ;;
     esac
   }
