Attempt running caddy as normal user

diff --git a/dots/scripts/containers/active/crowdsec/crowdsec b/dots/scripts/containers/active/crowdsec/crowdsec
--- a/dots/scripts/containers/active/crowdsec/crowdsec
+++ b/dots/scripts/containers/active/crowdsec/crowdsec
@@ -84,17 +84,17 @@ _containerize() {
   . "${_runconf}" || return 1
   unset _runconf
 
-  # Log the commands we use next
-  # Fail on errors
-  # Fail on unassigned
-  set -xeu
-
   # We don't use --security-opt no-new-privileges:true since
   # the AWS VPS that this runs on does not support that option
   _sec="--no-hosts --cap-drop=ALL"
   if command -v hostnamectl >/dev/null && [ "$(hostnamectl hostname)" = "nerd2" ]; then
     _sec="${_sec} --security-opt no-new-privileges:true"
   fi
+
+  # Log the commands we use next
+  # Fail on errors
+  # Fail on unassigned
+  set -xeu
 
   # Don't quote so that if user is empty it still expands
   #
