Add runconfig support

diff --git a/dots/scripts/containers/staging/openrct2/openrct2-server b/dots/scripts/containers/staging/openrct2/openrct2-server
--- a/dots/scripts/containers/staging/openrct2/openrct2-server
+++ b/dots/scripts/containers/staging/openrct2/openrct2-server
@@ -52,8 +52,24 @@ _check_user() {
 }
 
 _containerize() {
+  # OpenRCT2 runtime config variable
+  _or=""
+
+  # Source the runtime config (so we don't have to hardcode keys)
+  _runconf="${HOME}/.local/etc/containers/${_name}/runconfig.env"
+  if [ ! -e "${_runconf}" ]; then
+    printf -- 'You must provide %s\n' "${_runconf}"
+    return 1
+  fi
+
+  # Source the file into the environment
+  # shellcheck disable=SC1090
+  . "${_runconf}" || return 1
+  unset _runconf
+  readonly _or
+
   # Only compare the version minors
-  _current_version="$(podman --version | awk '{ print $3 }' | tr '.' ' ' | awk '{ print $1 "." $2}')"
+  _current_version="$("${_cmd}" --version | awk '{ print $3 }' | tr '.' ' ' | awk '{ print $1 "." $2}')"
   _is_cmd_new_enough="$(printf -- '%s' "${_current_version}" | awk '{ if ($1 >= 4.7) print 1; else print 0 }')"
   unset _current_version
 
@@ -71,9 +87,6 @@ _containerize() {
   # Fail on unassigned
   set -xeu
 
-  # This container uses the gluetun VPN network stack.
-  # Gluetun must be running before this container.
-
   # Don't quote so that if user is empty it still expands
   #
   # shellcheck disable=SC2086
@@ -81,6 +94,7 @@ _containerize() {
     --name "${_name}" --hostname "${_name}" \
     --security-opt no-new-privileges:true --cap-drop ALL \
     --init \
+    ${_or} \
     ${_network} \
     ${_mounts} \
     ${_ports} \
@@ -107,6 +121,20 @@ main() {
     _how="--rm -i -t"
   fi
   readonly _how
+
+  # Wait for the ${XDG_RUNTIME_DIR}/podman folder to be available before launching
+  # This folder is created "at some point" in response to podman commands being run
+  "${_cmd}" --version >/dev/null 2>&1 || {
+    printf -- 'Unable to check %s version.\n' "${_cmd}"
+    return 1
+  }
+  while [ ! -d "${XDG_RUNTIME_DIR}/containers" ]; do
+    sleep 1 || {
+      printf -- 'Cancelled while waiting for container runtime to stand up.\n'
+      return 1
+    }
+  done
+  printf -- 'Container runtime is ready, start %s\n' "${_name}"
 
   park="$1"
   if [ -z "${park}" ]; then
