Add example bootloader

diff --git a/dots/scripts/linux/pyamsoft-settings/installer b/dots/scripts/linux/pyamsoft-settings/installer
--- a/dots/scripts/linux/pyamsoft-settings/installer
+++ b/dots/scripts/linux/pyamsoft-settings/installer
@@ -325,6 +325,38 @@ main() {
       done
       unset _file_or_folder
 
+      # Loop through boot
+      for _file_or_folder in ./boot/**/*; do
+        # Skip folders
+        if [ -d "${_file_or_folder}" ]; then
+          continue
+        fi
+
+        _file_dir="$(dirname "${_file_or_folder}")"
+        _file_name="$(basename "${_file_or_folder}")"
+        _install_dir="${_file_dir#\.\/}"
+
+        case "${_file_dir}" in
+        *)
+          # Copy file permissions and restrict all access to only the owner
+          _package_install "${_specific_tag}" "${_file_dir}" "${_install_dir}" "${_file_name}" "700" "700" || return 1
+          ;;
+        esac
+
+        unset _install_dir
+        unset _file_dir
+        unset _file_name
+        unset _file_or_folder
+      done
+      unset _file_or_folder
+
+      # cd back out
+      cd .. || {
+        printf -- 'Failed to cd out of target host directory: "%s"\n' "${_target_host_or_skip_host}"
+        return 1
+      }
+    fi
+
       # Loop through root (only install example files, we NEVER touch running root)
       for _file_or_folder in ./root/.*.example; do
         # Skip folders
