Install files into the system as part of the package

diff --git a/dots/scripts/linux/pyamsoft-settings/PKGBUILD b/dots/scripts/linux/pyamsoft-settings/PKGBUILD
--- a/dots/scripts/linux/pyamsoft-settings/PKGBUILD
+++ b/dots/scripts/linux/pyamsoft-settings/PKGBUILD
@@ -7,7 +7,7 @@ pkgname=pyamsoft-settings
 # shellcheck disable=SC2034
 pkgdesc="pyamsoft Settings"
 # shellcheck disable=SC2034
-pkgver=v2487.ca3ecd4d
+pkgver=v2488.81131921
 # shellcheck disable=SC2034
 pkgrel=1
 # shellcheck disable=SC2034
@@ -45,22 +45,146 @@ pkgver() {
   printf "v%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
 }
 
-package__hostname() {
-  hostnamectl hostname
+_package__hostname() {
+  if command -v hostnamectl >/dev/null; then
+    hostnamectl hostname || return 1
+  elif command -v hostname >/dev/null; then
+    hostname || return 1
+  fi
+
+  return 0
+}
+
+_package_install() {
+  _package_install__src_dir="$1"
+  _package_install__install_dir="$2"
+  _package_install__file="$3"
+  _package_install__dir_chmod="$4"
+  _package_install__file_chmod="$5"
+
+  msg2 "INSTALL: ${_package_install__src_dir}/${_package_install__file} -> ${_package_install__file}"
+
+  # Setup directory
+  mkdir -p "${_package_install__install_dir}" || {
+    error "Failed to create install directory: ${_package_install__install_dir}"
+    return 1
+  }
+  chmod "${_package_install__dir_chmod}" "${_package_install__install_dir}" || {
+    error "Failed to chmod install directory: ${_package_install__install_dir}"
+    return 1
+  }
+
+  # Install file
+  cp "${_package_install__src_dir}/${_package_install__file}" "${_package_install__install_dir}" || {
+    error "Failed to copy install file: ${_package_install__src_dir}/${_package_install__file}"
+    return 1
+  }
+  chmod "${_package_install__file_chmod}" "${_package_install__install_dir}/${_package_install__file}" || {
+    error "Failed to chmod install file: ${_package_install__install_dir}/${_package_install__file}"
+    return 1
+  }
+
+  # Replace any placeholders
+  sed --in-place "s/<<MY_USER>>/${_my_username}/g" "${_package_install__install_dir}/${_package_install__file}"
+
+  unset _package_install__file_chmod
+  unset _package_install__dir_chmod
+  unset _package_install__src_dir
+  unset _package_install__install_dir
+  unset _package_install__file
+  return 0
 }
 
 package() {
   # shellcheck disable=SC2154
-  cd "${srcdir}/dots/scripts/linux/pyamsoft-settings" || {
-    msg "Failed to cd into ${srcdir}/dots/scripts/linux/pyamsoft-settings"
+  cd "${srcdir}/dots/dots/scripts/linux/pyamsoft-settings" || {
+    msg "Failed to cd into ${srcdir}/dots/dots/scripts/linux/pyamsoft-settings"
     return 1
   }
 
-  # Open up the umask in case you are running something more restrictive
-  umask 0022
+  # We may want different codepaths for different machines
+  _my_hostname="$(_package__hostname)"
 
-  ls --color -l
-  pwd
-  msg "hi"
-  package__hostname
+  # This is an assumption that the user account you would consider "my user" is UID 1000
+  # at this point in the script, we are running as fakeroot, so we have to hard-assume this
+  _my_username="$(id -un 1000)"
+
+  # Turn on globbing options (bash specific, but PKGBUILDs are run in bash right?)
+  shopt -s globstar nullglob
+
+  # Loop through etc
+  for _file_or_folder in ./etc/**/*; do
+    # Skip folders
+    if [ -d "${_file_or_folder}" ]; then
+      continue
+    fi
+
+    _file_dir="$(dirname "${_file_or_folder}")"
+    _file_name="$(basename "${_file_or_folder}")"
+
+    # shellcheck disable=SC2154
+    _install_dir="${pkgdir}/${_file_dir#\.\/}"
+
+    case "${_file_dir}" in
+    */sudoers.d)
+      _package_install "${_file_dir}" "${_install_dir}" "${_file_name}" "750" "600" || return 1
+      ;;
+    *)
+      _package_install "${_file_dir}" "${_install_dir}" "${_file_name}" "755" "644" || return 1
+      ;;
+    esac
+
+    unset _install_dir
+    unset _file_dir
+    unset _file_name
+    unset _file_or_folder
+  done
+  unset _file_or_folder
+
+  # Loop through opt
+  for _file_or_folder in ./opt/**/*; do
+    # Skip folders
+    if [ -d "${_file_or_folder}" ]; then
+      continue
+    fi
+
+    _file_dir="$(dirname "${_file_or_folder}")"
+    _file_name="$(basename "${_file_or_folder}")"
+
+    # shellcheck disable=SC2154
+    _install_dir="${pkgdir}/${_file_dir#\.\/}"
+
+    case "${_my_hostname}" in
+    nerd1)
+      case "${_file_name}" in
+      crowdsec* | cscli | home-assistant | caddy | ddns)
+        msg2 "SKIP INSTALL ${_install_dir}/${_file_name} on ${_my_hostname}"
+        continue
+        ;;
+      *) ;;
+      esac
+      ;;
+    nerd2)
+      case "${_file_name}" in
+      gamelaunch | ddns)
+        msg2 "SKIP INSTALL ${_install_dir}/${_file_name} on ${_my_hostname}"
+        continue
+        ;;
+      *) ;;
+      esac
+      ;;
+    aws*) ;;
+    *) ;;
+    esac
+
+    _package_install "${_file_dir}" "${_install_dir}" "${_file_name}" "755" "755" || return 1
+
+    unset _install_dir
+    unset _file_dir
+    unset _file_name
+    unset _file_or_folder
+  done
+  unset _file_or_folder
+
+  unset _my_hostname
 }
diff --git a/dots/scripts/linux/pyamsoft-settings/install_settings b/dots/scripts/linux/pyamsoft-settings/install_settings
--- a/dots/scripts/linux/pyamsoft-settings/install_settings
+++ b/dots/scripts/linux/pyamsoft-settings/install_settings
@@ -1,13 +1,32 @@
 #!/bin/sh
 
 _clean() {
-  rm -rf ./dots ./pkg ./src ./*.tar.zst
+  rm -rf ./dots ./pkg ./src ./testing
 }
 
 main() {
   _clean
 
-  makepkg -sfci
+  if [ "$1" = "install" ]; then
+    makepkg -sfci
+  else
+    makepkg -sfc
+  fi
+
+  if [ "$1" = "test" ]; then
+    mkdir "./testing"
+    cd "./testing" || {
+      printf -- 'Failed to cd in to testing\n'
+      return 1
+    }
+
+    mv ../pyamsoft-settings*.tar.zst .
+    tar xvf ./*.tar.zst
+    cd .. || {
+      printf -- 'Failed to cd out of testing\n'
+      return 1
+    }
+  fi
 
   _clean
 
