Instead of granting the entire /dev/input grant ACLs on joystick devices

diff --git a/dots/scripts/linux/pyamsoft-settings/hosts/nerd1/opt/pyamsoft/sbin/gamelaunch b/dots/scripts/linux/pyamsoft-settings/hosts/nerd1/opt/pyamsoft/sbin/gamelaunch
--- a/dots/scripts/linux/pyamsoft-settings/hosts/nerd1/opt/pyamsoft/sbin/gamelaunch
+++ b/dots/scripts/linux/pyamsoft-settings/hosts/nerd1/opt/pyamsoft/sbin/gamelaunch
@@ -2,6 +2,8 @@
 
 # Privileged script, to be used with gamer script and sudoers set up
 
+__all_granted_candidates=""
+
 _check_user() {
   _check_me="$1"
   if ! id -u "${_check_me}" >/dev/null 2>&1; then
@@ -12,6 +14,133 @@ _check_user() {
   fi
 
   unset _check_me
+  return 0
+}
+
+_grant_joystick() {
+  _grant_target_user="$1"
+  _grant_real_user="$2"
+
+  if [ -z "${_grant_target_user}" ] || [ -z "${_grant_real_user}" ]; then
+    printf -- 'Unable to grant joystick facl to %s -> %s\n' "${_grant_target_user}" "${_grant_real_user}"
+
+    unset _grant_target_user
+    unset _grant_real_user
+    return 1
+  fi
+
+  # Find all candidate js devices
+  _grant_candidates=""
+  for _js in /dev/input/js*; do
+    if [ -e "${_js}" ] && [ "${_js}" != "/dev/input/js*" ]; then
+      if [ -z "${_grant_candidates}" ]; then
+        _grant_candidates="${_js}"
+      else
+        _grant_candidates="${_js} ${_grant_candidates}"
+      fi
+    fi
+    unset _js
+  done
+  unset _js
+
+  if [ -n "${_grant_candidates}" ]; then
+    for _js in ${_grant_candidates}; do
+      printf -- 'Grant facl access to %s for user %s (%s)\n' "${_js}" "${_grant_target_user}" "${_grant_real_user}"
+      setfacl -m "u:${_grant_real_user}:rw" "${_js}" || {
+        printf -- 'Failed to grant facl access to %s for user %s (%s)\n' "${_js}" "${_grant_target_user}" "${_grant_real_user}"
+
+        unset _js
+        unset _grant_candidates
+        unset _grant_target_user
+        unset _grant_real_user
+        return 1
+      }
+
+      if [ -z "${__all_granted_candidates}" ]; then
+        __all_granted_candidates="${_js}"
+      else
+        __all_granted_candidates="${_js} ${__all_granted_candidates}"
+      fi
+
+      unset _js
+    done
+  fi
+  unset _js
+
+  unset _grant_candidates
+  unset _grant_target_user
+  unset _grant_real_user
+  return 0
+}
+
+_revoke_joystick() {
+  _revoke_target_user="$1"
+  _revoke_real_user="$2"
+
+  if [ -n "${__all_granted_candidates}" ]; then
+    for _js in ${__all_granted_candidates}; do
+      printf -- 'Revoke facl access to %s for user %s (%s)\n' "${_js}" "${_revoke_target_user}" "${_revoke_real_user}"
+      setfacl -x "u:${_revoke_real_user}" "${_js}" || {
+        printf -- 'Failed to revoke facl access to %s for user %s (%s)\n' "${_js}" "${_revoke_target_user}" "${_revoke_real_user}"
+      }
+      unset _js
+    done
+  fi
+  unset _js
+
+  unset __all_granted_candidates
+
+  unset _revoke_target_user
+  unset _revoke_real_user
+  return 0
+}
+
+_run0() {
+  _run0_target_user="$1"
+  _run0_real_user="$2"
+
+  if [ -z "${_run0_target_user}" ] || [ -z "${_run0_real_user}" ]; then
+    printf -- 'Unable to run0 %s -> %s\n' "${_run0_target_user}" "${_run0_real_user}"
+    return 1
+  fi
+
+  # Eat arguments, leave rest
+  shift
+  shift
+
+  # Groups explanation:
+  # "pipewire" - Faster sound performance (will still work without but may see more XRUNs)
+  #
+  # Previous groups
+  # "input" - Grants access to Controller/Joystick
+  #           Instead of giving entire group (and this would allow keyboard input sniffing, use facl to grant joysticks)
+  readonly _extra_groups="pipewire"
+
+  printf -- '[gamelaunch] Running command: [%s] "~/bin/launcher %s"\n' "${_run0_target_user}" "$*"
+  printf -- '[gamelaunch] Running command as target user: %s\n' "${_run0_real_user}"
+  printf -- '[gamelaunch] Running command with extra groups: %s\n' "${_extra_groups}"
+  printf -- '[gamelaunch] DISPLAY=%s\n' "${DISPLAY}"
+  printf -- '[gamelaunch] XAUTHORITY=%s\n' "${XAUTHORITY}"
+  printf -- '[gamelaunch] GAMER_GAMESCOPE=%s\n' "${GAMER_GAMESCOPE:-0}"
+  printf -- '[gamelaunch] GAMER=1\n'
+
+  # Running machinectl shell gives us a "clean session to work with" that attaches to it's own systemctl --user session
+  # and loginctl session
+  #
+  # Because its "clean" though, we need to manually forward our main user session "$DISPLAY" and "$XAUTHORITY"
+  # to allow x11 connections.
+  #
+  # DO NOT FORWARD "$WAYLAND_DISPLAY" yet as multi-user on the same display isn't fully figured out yet (things crash).
+  #
+  # We want this 'raw ~' to not expand so that it is evaluated as the target_user home, not main_user home
+  # shellcheck disable=SC2088
+  /usr/sbin/run0 \
+    --property="SupplementaryGroups=${_extra_groups}" \
+    --user="${_run0_real_user}" \
+    --setenv="DISPLAY=${DISPLAY}" --setenv="XAUTHORITY=${XAUTHORITY}" \
+    --setenv="GAMER_GAMESCOPE=${GAMER_GAMESCOPE:-0}" \
+    --setenv="GAMER=1" \
+    /bin/bash -l -c '~/bin/launcher' "$@" || return 1
   return 0
 }
 
@@ -86,35 +215,19 @@ main() {
     return 1
   fi
 
-  # input - Game controllers
-  # pipewire - Faster sound performance (will still work without but may see more XRUNs)
-  readonly _extra_groups="input pipewire"
+  # Grant facl for controller/joystick
+  _grant_joystick "${_target_user}" "${_real_user}" || {
+    _revoke_joystick "${_target_user}" "${_real_user}"
+    return 1
+  }
 
-  printf -- '[gamelaunch] Running command: [%s] "~/bin/launcher %s"\n' "${_target_user}" "$*"
-  printf -- '[gamelaunch] Running command as target user: %s\n' "${_real_user}"
-  printf -- '[gamelaunch] Running command with extra groups: %s\n' "${_extra_groups}"
-  printf -- '[gamelaunch] DISPLAY=%s\n' "${DISPLAY}"
-  printf -- '[gamelaunch] XAUTHORITY=%s\n' "${XAUTHORITY}"
-  printf -- '[gamelaunch] GAMER_GAMESCOPE=%s\n' "${GAMER_GAMESCOPE:-0}"
-  printf -- '[gamelaunch] GAMER=1\n'
+  _run0 "${_target_user}" "${_real_user}" "$@" || {
+    _revoke_joystick "${_target_user}" "${_real_user}"
+    return 1
+  }
 
-  # Running machinectl shell gives us a "clean session to work with" that attaches to it's own systemctl --user session
-  # and loginctl session
-  #
-  # Because its "clean" though, we need to manually forward our main user session "$DISPLAY" and "$XAUTHORITY"
-  # to allow x11 connections.
-  #
-  # DO NOT FORWARD "$WAYLAND_DISPLAY" yet as multi-user on the same display isn't fully figured out yet (things crash).
-  #
-  # We want this 'raw ~' to not expand so that it is evaluated as the target_user home, not main_user home
-  # shellcheck disable=SC2088
-  exec run0 \
-    --property="SupplementaryGroups=${_extra_groups}" \
-    --user="${_real_user}" \
-    --setenv="DISPLAY=${DISPLAY}" --setenv="XAUTHORITY=${XAUTHORITY}" \
-    --setenv="GAMER_GAMESCOPE=${GAMER_GAMESCOPE:-0}" \
-    --setenv="GAMER=1" \
-    /bin/bash -l -c '~/bin/launcher' "$@"
+  _revoke_joystick "${_target_user}" "${_real_user}"
+  return 0
 }
 
 main "$@" || exit 1
